### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by SaucissePuree** [kwpugh/gobber#1]
Hi and Thanks for this mod :)
May i suggest you to name your file with the same name as your mod?
It's easier to find a mod in a modpack when it keeps its original name . (it should be Gobber-1.12.2_1.1.34)
Thanks again and keep it up ;)
(my english sucks, sorry)

**Comment by kwpugh** [comment]
Great point, I will update.

Thanks.

**Comment by kwpugh** [comment]
Completed
