### ISSUE TITLE
Step Assist

### ISSUE THREAD

**Issue by TookUrSweetRoll** [kwpugh/Gobber#1]
Unequipped armor, effect still applies.

**Comment by kwpugh** [comment]
I had noticed that, it clears after relogging.

I will continue to investigate methods to correct that.

**Comment by kwpugh** [comment]
Are you experiencing this on single player or a server?

A couple of version ago I added a check to see if the boots are being worn.  I just checked v.27 from Curseforge and no step assist is active when the books are removed.

Can you confirm what version you are using?

**Comment by TookUrSweetRoll** [comment]
Apologies, I was on v.24. Downloaded v.28 and working perfectly. Thank you.
