### ISSUE TITLE
Config options do not work properly

### ISSUE THREAD

**Issue by MinCrin** [kwpugh/Gobber#1]
When set to "true", the option to disable the Glucky Block does not actually disable the generation.

    # Set to true to disable the Glucky Block [default: false]
    B:worldgenGlucky=true

**Comment by MinCrin** [comment]
https://imgur.com/a/6YeSnFb

Screenshot of world, keep in mind above config option is set to true for disable.

**Comment by kwpugh** [comment]
Did you explore into a "new" chunk that had not been explored yet?   It will not remove blocks from world gen, just prevent from spawning in "new" chunks.

**Comment by kwpugh** [comment]
My bad, I forgot to put the conditional around the event registration.  Will be fixed in next release later tonight.

**Comment by kwpugh** [comment]
I just uploaded v1.1.136 to CurseForge which addresses the Glucky Block issue.
