### ISSUE TITLE
1.14.4 staff of harvest - does not work with netherwart

### ISSUE THREAD

**Issue by Knito58** [kwpugh/gobber#1]
... but else is a fantastic tool. Even better in coop with the ring of attraction.

MC 1.14.4
Forge 20.0.75
Gobber 2 v. 2.1.86

**Comment by kwpugh** [comment]
I will add nether wart breaking for v89.  It won't re-plant but will simple break like sugar cane and cactus currently do.

**Comment by Knito58** [comment]
Sorry didn't know it was intended behaviour. Yep breaking netherwarts in the range is cool enough.
Thank you.
