### ISSUE TITLE
[1.14.4] Gobber plants don't give a product when right clicked if your hand isn't empty.

### ISSUE THREAD

**Issue by ProsperCraft** [kwpugh/gobber#10]
Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

If you right click harvest a gobber plant with a ring of the farmer for example you don't get a product unless your hand is empty.

Gobber2-1.14.4-2.1.100

forge-1.14.4-28.1.40

**Comment by ProsperCraft** [comment]
The plant dissapears as well if you break it with something.

**Comment by kwpugh** [comment]
I continue to investigate the harvest with a non-empty hand.  So far the alternatives have not worked.

As to the plant break dropping nothing, that is intended to keep the value of gobber seeds high.

**Comment by kwpugh** [comment]
Ok, this will be fixed in the next release v106.    The way it will work now is: breaking a plant will only drop the seed and right-clicking will harvest (empty or full hand).
