### ISSUE TITLE
[1.17] Ring of Attraction [FABRIC] crash when starting Minecraft

### ISSUE THREAD

**Issue by EvilErwin** [kwpugh/gobber#100]
When i start Minecraft with the "Ring of Attraction [FABRIC]" mod installed i get this error:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ring_of_attraction'!
Exit-Code: -1"

Software:
- Windows 10
- Minecraft 1.17
- Fabricloader 0.7.4 (downloaded today 2021.06.20)
- RingOfAttraction-Fabric-1.17-1.1.9.jar (downloaded today 2021.06.20)
- fabric-api-0.36.0+1.17.jar (downloaded today 2021.06.20)
- java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

Additional infos are in the crash report.

[crash-2021-06-20_20.27.15-client.txt](https://github.com/kwpugh/gobber/files/6682903/crash-2021-06-20_20.27.15-client.txt)

**Comment by kwpugh** [comment]
You are missing Cloth Config API, which is required.

**Comment by EvilErwin** [comment]
Thanks.
Now it works fine.
I was in Minecraft 1.16.5 before and i did not need "Cloth Config API" for your mod.
And i could swear "Cloth Config API" was not listet as a "Required Dependency" on the curseforge.com-page for RingOfAttraction-Fabric-1.17-1.1.9.jar when i downloaded it.
Or my memory is faulty.

**Comment by kwpugh** [comment]
I had to start using Cloth Config for the config features with 1.17.
