### ISSUE TITLE
[RING OF GROWTH STANDALONE] Ring of Growth not working for Immersive Enginnering industrial hemp

### ISSUE THREAD

**Issue by Cynix32** [kwpugh/gobber#102]
MC 1.16.5
Forge 36.2.2
Ring of Growth Standalone
Immersive Engineering
{Mod compatibility issue}

Ring of Growth does not seem to be working with industrial hemp plant from Immersive Engineering.

**Comment by kwpugh** [comment]
I'll take a look.

**Comment by kwpugh** [comment]
Added to 1.18.1 version of stand alone ring and ring and staff in Gobber.  No back ports.
