### ISSUE TITLE
[1.17.1] EndHammer/EndExcavator 5x5 mode changes for all players on servers

### ISSUE THREAD

**Issue by DadBackFromWalmart** [kwpugh/gobber#104]
We have a private multiplayer server running Gobber 2 on Fabric for MC 1.16.5.

3 players have the End Hammer, and when one player is switching the scale from 3x3 to 5x5 or 5x5 to 3x3, the change occurs for all players with the Hammer, regardless of whether it is their actively held item.

List of Mods:
(client)
![image](https://user-images.githubusercontent.com/61283820/127585775-7cc22e50-28ca-4d56-a7b5-ea71e52e9c9f.png)

(server)
![image](https://user-images.githubusercontent.com/61283820/127585822-e969de86-53e1-4e48-b665-a49828d51872.png)

I'm not sure if this is a mod compat bug, or if it's to do with us being on a multiplayer server, but it sure is weird.

If there's anything more I can add to help you, please let me know.

**Comment by DadBackFromWalmart** [comment]
Oh and I think the Fabric version is 0.11.6, based on what the Installer says when installing the profile... if that's helpful.

**Comment by kwpugh** [comment]
I have a strong feeling I know what it is.   I think with Fabric I'm going to have to save each Hammer's setting to the item's NBT, so each hammer is different than the next.   This may take me a bit.

**Comment by DadBackFromWalmart** [comment]
Hey no worries man, I really appreciate you looking into it and the quick reply! Let me know if I can be of any help.

**Comment by DadBackFromWalmart** [comment]
Thinking about it this morning - we didn't come across this yesterday, but I'd be curious to see if this kind of bug affects the End Excavator as well. Like, wondering if this extends to other items that have changeable settings like that. We haven't noticed it with any rings / medallions, but perhaps that's because they apply known status effects.

**Comment by kwpugh** [comment]
That would be true of the excavator as well, since they use the same logic for changing 3x3 to 5x5.

You might have them enchant their hammers/excavators to see if it keeps happening.  I'm not sure, but if the items get a unique NBT, via enchantment, that might stop it.  In the short run until I fix it.

**Comment by DadBackFromWalmart** [comment]
Interesting. I know I have enchants on mine - I will see however if they all have the same enchants, or any at all, and test it a bit more.

**Comment by kwpugh** [comment]
Can you give this version a try and see if if they still change modes together?

[Gobber2-Fabric_1.16.5-2.3.74.jar.zip](https://github.com/kwpugh/gobber/files/6910602/Gobber2-Fabric_1.16.5-2.3.74.jar.zip)

**Comment by DadBackFromWalmart** [comment]
Will give it a look here shortly. Thank you!

**Comment by DadBackFromWalmart** [comment]
Just tried it - not working for either the End Hammer nor the Excavator

**Comment by kwpugh** [comment]
ok, this could be awhile before I figure this out.  To avoid confusion among players, I would suggest disabling the 5x5 feature in the config.

**Comment by DadBackFromWalmart** [comment]
Mind you, this is in 1.16.5, not 1.17.1

**Comment by kwpugh** [comment]
I know, but I will create the fix in 1.17.1 and then back port to 1.16.5, if I can figure this out.

**Comment by DadBackFromWalmart** [comment]
Gotcha, that makes sense.

**Comment by DadBackFromWalmart** [comment]
If there is anything else I can do to help you get it figured out, don't hesitate to let me know.

**Comment by kwpugh** [comment]
I'm good, I know exactly what is wrong and what needs to be done, I just need to figure out how to implement it.

**Comment by DadBackFromWalmart** [comment]
👍

**Comment by kwpugh** [comment]
[Gobber2-Fabric_1.16.5-2.3.74.jar.zip](https://github.com/kwpugh/gobber/files/6914046/Gobber2-Fabric_1.16.5-2.3.74.jar.zip)


So I re-wrote the end hammer logic.  Can you try out the End Hammer in this version?  I did not do the excavator yet.
It appears to work in dev, but I have no way to test with multiple players on a server.

Thank you.

**Comment by DadBackFromWalmart** [comment]
Will do as soon as I'm able. I'm off work tomorrow but others on server all have day jobs, so it might be about 18 hours from now that I'm able to do so.

**Comment by kwpugh** [comment]
cool, thanks.  Make you test by actually making the end hammer, not pulling it out of creative.

**Comment by kwpugh** [comment]
Actually, use this one, I added the code to the excavator as well.

[Gobber2-Fabric_1.16.5-2.3.74.jar.zip](https://github.com/kwpugh/gobber/files/6917179/Gobber2-Fabric_1.16.5-2.3.74.jar.zip)

The way I solved it is by giving each hammer/excavator their own stored values that are read when changing modes.  Added bonus is if you have two in your inventory, you can have one set to 3x3 and one to 5x5.

![Screen Shot 2021-08-02 at 8 16 54 AM](https://user-images.githubusercontent.com/8809210/127868667-63a33015-105d-4950-8f64-36a292ef8647.png)

**Comment by DadBackFromWalmart** [comment]
The fix works for both Hammer and Excavator, however, only for newly crafted items, and those crafted after the fix.

Existing Hammers and Excavators, as well as those given in Creative Mode, do not seem to switch modes, and only remove one block at a time, instead of doing a 3x3 or 5x5 grid, using this new .jar on Fabric.

**Comment by kwpugh** [comment]
yes, only newly crafted hammers will have the correct behavior.  And, I have not figured out how to add the required tags to items pulled from creative.  Ok, I'm going to publish the updated version for 1.16 and 1.17.  thank you for your help.

**Comment by kwpugh** [comment]
I figured out how to make it work when pulled out of creative as well, yay.   An updated version will be out shortly.

Thank you for your help.
