### ISSUE TITLE
[1.17.1] Ring of Repair fills TAN water canteens

### ISSUE THREAD

**Issue by susan3333333** [kwpugh/gobber#105]
My water is always full.....LOL

I guess this would probably affect any multi-use item?

**Comment by kwpugh** [comment]
Yeah, pretty much.  I added it to my list of things to work on in future versions.

**Comment by susan3333333** [comment]
Is there anyway I could "blacklist" the item in the meantime?

**Comment by kwpugh** [comment]
Are you using Gobber or the Ring of Repair mod?

**Comment by kwpugh** [comment]
So looking at.  my code, I only repair items. that meet both of these conditions:

if (target.isDamaged() && target.getItem().isRepairable(target))

TAN source code is not publicly available, so I can not see. what they are doing.  I suspect that they have set the isRepairable,   which. doesn't really make sense for a canteen.

**Comment by susan3333333** [comment]
Hi, I am using the standalone mod.
The Canteen is actually set as a repairable item??????
Maybe it's easier to handle the refills by using damage/repair I guess?

**Comment by kwpugh** [comment]
The point is I have no idea if it is set to repairable, since I cannot see the TAN source code.  But considering it is passing through my repair logic, I assume it is.

**Comment by susan3333333** [comment]
Oh, ok.

**Comment by kwpugh** [comment]
Nothing I can do about this one.  You will need to ask the TAN author.
