### ISSUE TITLE
Is curios support enabled for Gobber Forge 1.17.1 2.5.2?

### ISSUE THREAD

**Issue by Baggytrousers27** [kwpugh/gobber#106]
Running curios-forge-1.17.1-5.0.0.1 on 37.0.50 at present and have 2 rings slots but Gobber rings don't fit it in them so they're likely some other mods'. No worries if it isn't, just checkin that my installation hasn't broken itself ... again. Got a backpack set aside specially for them anyway.

**Comment by kwpugh** [comment]
Gobber 1.17.1 does not support curios.
