### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by firestorm2039** [kwpugh/gobber#108]
do i only need 1 ring? or will things repair faster the more things i have?
does it do all items at once or 1 at a time?

is there a way to alter the time it take to repair? as my enchanted emerald stuff does not really seem to be repairing itself, i cant repair it on an anvil as it says "costs to much", so this ring is my only option

**Comment by kwpugh** [comment]
the ring will  repair one item at a time, if it is damaged  and it is repairable.  There is an option in the config to lower the interval for repair.

If you have further questions, you might want to join my Discord: https://discord.gg/KSD6n3eX
