### ISSUE TITLE
Duping with Hammer

### ISSUE THREAD

**Issue by Old-Man-D** [kwpugh/gobber#11]
I've just built the end hammer and I notice that is does not give the correct amount of blocks back.  It could be that I enchanted it with silk touch, but now it give me both the silk touch block and the non silk touch block.  So mining stone gives me the full amount of stone and the full amount of cobble stone.  Mining diamond gives me the diamonds and the diamond ore.  I have not tried the other hammers, I just went straight to the end one.

**Comment by kwpugh** [comment]
I will take a look this evening.

**Comment by kwpugh** [comment]
Fixed in the latest release
