### ISSUE TITLE
Ring of Repair Standalone

### ISSUE THREAD

**Issue by ByucknahTheRed** [kwpugh/gobber#111]
The Ring of Repair does not want to repair items that are currently being held. Also does not seem to repair spartan shields at all?

I am using 1.16.5 Minecraft.

**Comment by kwpugh** [comment]
the ring is designed to exclude the item in hand.

**Comment by kwpugh** [comment]
Spartan Shields may not have the isRepairable tag.  It is closed source, too I can't tell.

**Comment by ByucknahTheRed** [comment]
> 
> 
> the ring is designed to exclude the item in hand.

I don't suppose there is a possibility that there will ever be a config option to include held items?

Also, good to know about the shields. Seems strange the weapons have no issues but the shields wont repair. Thank you.

**Comment by kwpugh** [comment]
the problem with ticking the main hand item is the responds with a whole twitch to the arm, very distracting.

plus, the idea of repairing an item actually being used seems a bit much
