### ISSUE TITLE
[1.17.1] Gobber ores does not generate 

### ISSUE THREAD

**Issue by Minecarthus** [kwpugh/gobber#112]
Hello, 

Gobber ores does not generate
i compilated with the command "./gradlew build" and took the mod in the "\build\libs" folder
(i haven't modified the mod)

**Comment by kwpugh** [comment]
Kind  of hard to know if you are not using a published version.
 
Do you have the issue using the version published on Curseforge ?

**Comment by Minecarthus** [comment]
No i don't have it with curseforge :/

**Comment by Minecarthus** [comment]
I will verify on the latest curseforge build

**Comment by Minecarthus** [comment]
So, i tried to update forge and it worked perfectly !
also thanks for your quick response
have a good day

**Comment by kwpugh** [comment]
no problem, enjoy.
