### ISSUE TITLE
[1.16.5 Bug] Hammer destroying indestructible blocks

### ISSUE THREAD

**Issue by PapiOphidian** [kwpugh/gobber#113]
Some modded blocks are indestructible, which cannot be broken by the hammer directly, but can be broken if the block is within the outside ring of effect.

This could possibly extend to other tools if some blocks extending some base materials can be effected by their respective tools, but I have not tested.

I have tested this against bedrock and bedrock is fine as usual. Just modded blocks (specifically I tested compact machines)

**Comment by kwpugh** [comment]
I see the problem.

**Comment by kwpugh** [comment]
This block?   

![Screen Shot 2021-12-04 at 8 47 53 PM](https://user-images.githubusercontent.com/8809210/144731523-cb21008e-f232-4b2b-a132-866bea4313dc.png)

**Comment by kwpugh** [comment]
Can you test this to make sure I got it?

[Gobber2-Forge-1.16.5-2.3.52.jar.zip](https://github.com/kwpugh/gobber/files/7655122/Gobber2-Forge-1.16.5-2.3.52.jar.zip)

**Comment by PapiOphidian** [comment]
Can do first thing in the morning. Sorry for delays

**Comment by PapiOphidian** [comment]
Just got around to testing at it works just fine 👍
Also tested against security craft unbreakable blocks and those are fine as well which was also a concern I had

**Comment by kwpugh** [comment]
Ok, cool, thanks for confirming.  I will publish the new version shortly.

**Comment by kwpugh** [comment]
fixed in v52
