### ISSUE TITLE
[1.18.1] Ring does not function when in curios ring slot

### ISSUE THREAD

**Issue by Shedao-Shai** [kwpugh/gobber#115]
Mod version 1.18.1-1.4.2
Curios 1.18-5.0.2.4
Forge 1.18.1-39.0.5

The ring of repair does not function when put in the curios ring slot like one would expect, however it _does_ function per normal when in the player's inventory. Other rings (attraction) function as normal when in the ring slot, it is specific to the repair ring.

**Comment by kwpugh** [comment]
Gobber no longer supports curios in 1.18.1.  The slot can only be used for storage.
