### ISSUE TITLE
Ring does not repair items when held in hand

### ISSUE THREAD

**Issue by Shedao-Shai** [kwpugh/gobber#116]
Mod version 1.18.1-1.4.2
Forge 1.18.1-39.0.5

When in inventory ring repairs items sequentially as expected, but it will _not_ repair an item if it is held in the player's hand or offhand. If moved out of the player's hand repair continues as normal.

**Comment by kwpugh** [comment]
This is by design.  It will not repair an item in the player's mainhand.
