### ISSUE TITLE
Question, should i make more than 1?

### ISSUE THREAD

**Issue by firestorm2039** [kwpugh/gobber#117]
posting here as there is no "comments" section showing?.

i understand this repairs 1 item at a time yes? will having 2 or 3 in my inventory repair more or repairing 1 item faster? or does it make no difference?
i have very strong items that take ages to repair themselves and are to high a level to repair using anvil.

**Comment by kwpugh** [comment]
having  two rings will speed up,  but beyond that is  diminishing returns.

**Comment by kwpugh** [comment]
questions are best for Discord:  https://discord.gg/j7bYbkW
