### ISSUE TITLE
[1.18.1] End Tree Axe - Destroying anything that is not wood material.

### ISSUE THREAD

**Issue by HelixCreations** [kwpugh/gobber#118]
If you use the End Tree Axe on anything that is not "wood" it will destroy it and remove it entirely from your world.

**Comment by kwpugh** [comment]
I've been researching  this for a  few days and still no clue why this is happening.

**Comment by HelixCreations** [comment]
> I've been researching this for a few days and still have no clue why this is happening.

Yeah, when it happened the first few times I thought it was another mod doing it. But yeah noticed when I had it in my hand and I had broken a Battery from the mod Cyclic and noticed it does do it on anything apart from wood material. :( 

Could it be an ID thing? Just guessing, total noob here when it comes to Java.

Best of luck with finding it. :)

**Comment by kwpugh** [comment]
I  don't think  so.  I think it is somehow related to how Forge handles effective materials.   I  have essentially the  same code for the Fabric version of the tree axe and it does not happen  there.

**Comment by kwpugh** [comment]
Fixed in v2.6.12
