### ISSUE TITLE
[1.18.1] {2.6.10} Night Vision

### ISSUE THREAD

**Issue by hornertom** [kwpugh/gobber#119]
Vision ring not working, but also night vision potions from vanilla are not working. Not sure if your mod is having a conflict with it.

The only night vision im able to get is from Vision Helmet from the mod Cyclic. Not sure if that helps or if you think its a conflict with cyclic.

**Comment by kwpugh** [comment]
Are you using any performance-enhancing mods like sodium, lithium, etc?   If so, there are some config settings to deal with that.  Those mods lower the player tick interval causing the night vision and other effect items to not "catch" and engage.  The config setting allows you to increase the default interval for the effects.

**Comment by kwpugh** [comment]
actually, this is forge, I never added those options.

**Comment by kwpugh** [comment]
Also, try the Ring of Swiftness and Ring of Haste and see if they work.

**Comment by hornertom** [comment]
> Also, try the Ring of Swiftness and Ring of Haste and see if they work.

Both of them are working fine with me, I do use Optifine, but in the previous 1.18 version it was working fine.

**Comment by kwpugh** [comment]
Dos night vision work without Optifine?

**Comment by hornertom** [comment]
Just tested without optifine and still nothing.

**Comment by kwpugh** [comment]
Did you try giving yourself night vision with the /effect command?  Note any error that might result from that?

I can not replicate on my side, so I have nothing to go on.   The fact that vanilla night vision potions don't work, make me think some mod you have has broken it.

**Comment by hornertom** [comment]
> Did you try giving yourself night vision with the /effect command? Note any error that might result from that?
> 
> I can not replicate on my side, so I have nothing to go on. The fact that vanilla night vision potions don't work, make me think some mod you have has broken it.

Going to guess you are right, i cant give myself night vision with the /effect command. Im going to try and reach out to the Cyclic mod dev, since it seems the only night vision i can get is from his mod night vision helmet.

**Comment by kwpugh** [comment]
I'm playing around with cyclic, the code for the helmet seems unusual to me, not sure if it is checking if the helmet is wore and if not, remove the night vision effect.  I'm testing now.

**Comment by hornertom** [comment]
Thanks for that, i also opened an issue with the mod author, but if there is a quick fix that i can replicate until he fixes it i would appreciate it.

**Comment by kwpugh** [comment]
I did some testing with Cyclic, ring of vision works fine and the /effect command does as well, so I don't think Cyclic is causing the issue.

**Comment by kwpugh** [comment]
can you post a link to your latest.log which shows all the mods you are running?

**Comment by hornertom** [comment]
[latest.log](https://github.com/kwpugh/gobber/files/7833332/latest.log)

**Comment by kwpugh** [comment]
Can you try a game restart and then send it to me?  the file is just file of blocks messages.

**Comment by hornertom** [comment]
hope that works 

[https://paste.shockbyte.com/izihusirazadukapolig](url)

**Comment by kwpugh** [comment]
nothing there with that link.

**Comment by hornertom** [comment]
sorry about that lets try this again, it seems to have the mod list
[latest.log](https://github.com/kwpugh/gobber/files/7833786/latest.log)

**Comment by kwpugh** [comment]
I would suggest you start removing mods until it starts working, that is the only way to find out at this point.
