### ISSUE TITLE
End armor cant fly in end

### ISSUE THREAD

**Issue by Old-Man-D** [kwpugh/gobber#12]
I've got another one, I cant seem to fly while using the end armor in the end.  I just updated to the version you put out earlier today.

**Comment by kwpugh** [comment]
Flying with End Armor was removed in 1.14.4 version.

**Comment by Old-Man-D** [comment]
ok, thanks.  The in game tool text still says that it provides flight, so I was confused.

**Comment by kwpugh** [comment]
I will correct the text, sorry for missing that.
