### ISSUE TITLE
Gobber Broken?

### ISSUE THREAD

**Issue by jxyke** [kwpugh/Gobber#12]
I'm getting a strange bug.

I installed Gobber 2 into my already modded minecraft (22+ mods) and found that, after installing Gobber 2, 1 of my vanilla creative tabs and 2 of my modded creative tabs were missing completely, and the Gobber 2 creative tab was completely empty.

I uninstalled every mod BUT Gobber, and found that the exact same thing happened. This time only the 1 vanilla creative tab was missing, and the Gobber 2 creative tab was completely blank. This is using the latest version of Gobber with Forge 28.0.40 (I'm using forge 28.0.40 because none of my other mods work with 28.0.45 for some reason, they all "fail to load correctly")

I know that a bunch of issues are gonna come up because 1.14.4 is still VERY VERY new to the modding community, but I would appreciate some help, I've never seen this before!

**Comment by jxyke** [comment]
Update: downgrading to Gobber 2.1.76 solved this issue completely, it seems to only happen with Gobber 2.1.77.

**Comment by kwpugh** [comment]
Yes. Gobber 77 is built with Forge 45.  Due to changes in Forge 45, all mods in a given pack or installation must be updated to 45.   Mod authors are updating, so this should pass shortly.  Stay with Gobber 76 until all the mods you use update to Forge 45.
