### ISSUE TITLE
Doesn't unlock curios ring slot(ring of repair) in 1.18

### ISSUE THREAD

**Issue by amandexspeed** [kwpugh/gobber#123]
I have the last curios mod and this mod doesn't unlock curios slot

**Comment by kwpugh** [comment]
the  mod doesn't support Curios.

**Comment by amandexspeed** [comment]
why? In the description of the mod it says it have curios integration.And a question: I didn't notice any restauration of the mod in my armour.It's a issue or conf that maybe causing this problem?

**Comment by kwpugh** [comment]
<img width="828" alt="Screen Shot 2022-01-26 at 5 57 27 PM" src="https://user-images.githubusercontent.com/8809210/151266778-08950ba2-f6c5-45d4-b9b6-184c96126cd3.png">

Dropped Curios  in 1.17

**Comment by amandexspeed** [comment]
Ok, I download a smaller mod called ring of restauration that brings me here for reports that i'm trying to use but the repairing isn't working. Do you know what is happening?

**Comment by kwpugh** [comment]
ring of repair?   I  guess you may  be translating.    it only does one item at a time and will not repair the item in your hand.

**Comment by amandexspeed** [comment]
I'm speaking about this mod
![Screenshot_19](https://user-images.githubusercontent.com/60000299/151267823-187a9673-c3b5-4be2-8206-7af9e960b260.png)

**Comment by amandexspeed** [comment]
I tried repairing in a lot of ways but i doesn't works

**Comment by kwpugh** [comment]
It does not repair durability while the ring is in your inventory?

**Comment by amandexspeed** [comment]
yeah, I use a mod that shows durability and it shows me that the itens keep their durability and i played for a lot of minutes

**Comment by kwpugh** [comment]
keep in mind it does armor last and will not repair an item in main  hand

**Comment by amandexspeed** [comment]
I realized that it restored my diamond tools durability 🙈🙈🙈🙈 sorry for disturbing .

**Comment by kwpugh** [comment]
no problem, enjoy

**Comment by amandexspeed** [comment]
😊😊😊😊 Thanks! Your mod are excellent.
