### ISSUE TITLE
Ring of repair will not go into ring slot on Curios

### ISSUE THREAD

**Issue by PernDragon** [kwpugh/gobber#124]
I created the Ring of repair and tried to wear it.  Perhaps I'm doing something wrong?
Anyways it will not go into the side slot for rings in the Curios mod.  
Please help, Thanks in advance and thank you for making such a great mod and keeping it up to date.

**Comment by kwpugh** [comment]
Are you on 1.18.1 ?

**Comment by PernDragon** [comment]
Yes sir

**Comment by kwpugh** [comment]
Curios was dropped aft 1.16.5, so it is no longer used.

**Comment by PernDragon** [comment]
Oh Ok, How do I use the ring?  just place it in a hot key and right click?

**Comment by kwpugh** [comment]
just have in your inventory and it does its work.

**Comment by PernDragon** [comment]
Very Nice, Thank you for your help, We can Close this

**Comment by kwpugh** [comment]
Enjoy.
