### ISSUE TITLE
Damages

### ISSUE THREAD

**Issue by GrandBrandle** [kwpugh/gobber#125]
In the 1.18 download the weapons damages are severely reduced. Unknown if this was intentional, if so please ignore

**Comment by kwpugh** [comment]
which version?  how much reduced?

**Comment by GrandBrandle** [comment]
in the most recent version of the gobber mod 1-2.6.18 the damage on all the tools has been dropped by 8 points for everything. bring the swords from 11 for the gobber sword to 3, damage on the nether gobber sword from 13 to 5, and damage on the end gobber sword from 16 to 8. This is consistent through all the tools and weapons.

**Comment by kwpugh** [comment]
If you had a previous version, delete your gobber config file and let the new defaults kick in.  I change the scaling in the config.

**Comment by GrandBrandle** [comment]
This worked wonderfully, thank you for the help I will keep this in mind for future updates.

**Comment by kwpugh** [comment]
enjoy
