### ISSUE TITLE
[1.18.1] DragonKillHandler.java doesn’t seem to function properly.

### ISSUE THREAD

**Issue by daftprophet** [kwpugh/gobber#126]
Using on a 1.18.1 server, and it is installed properly within the files. Entire mod functions properly, but dragon egg does not respawn?

**Comment by kwpugh** [comment]
Please post a copy of your recent system log so I can see what might be going o

**Comment by daftprophet** [comment]
[latest.log](https://github.com/kwpugh/gobber/files/8103100/latest.log)
This is startup. we can't seem to find one that includes the kill of the e dragon
We can redo to find one, since that should be the one you're after?

**Comment by kwpugh** [comment]
you do have the config option for the egg drop set to true in the config, correct.

I went on a fresh server with just GObber and tested the multiple drops and it worked fine.  I'm guessing you have another mod that might be interfering with the dragon death event.   Do you have any mods the change up things in the end or the dragon fight?

**Comment by daftprophet** [comment]
The only one that I can see that affects the end (to my own knowledge) is Valhesia 4, 1.18.1. It started to change the end as of Valhesia 3 but I can't find anything else that would do it.

**Comment by kwpugh** [comment]
You do have the dragon egg config option set to true, correct?

**Comment by daftprophet** [comment]
We double checked it and no, it was set to false. I guess he never actually check the config, whoops. Sorry for the inconvenience.

**Comment by kwpugh** [comment]
No problem, glad  it is resolved.  Enjoy  playing.
