### ISSUE TITLE
[1.18.1] night vision and glow effect not working

### ISSUE THREAD

**Issue by Ashtar084** [kwpugh/gobber#127]
please can fix?
just not work 
glow effect and nigth vision

1.18.1 Forge

**Comment by kwpugh** [comment]
Seems  to work  fine.

![2022-02-20_10 22 33](https://user-images.githubusercontent.com/8809210/154852761-d044e0ab-6f74-41f4-a9be-ed313b06d827.png)

**Comment by kwpugh** [comment]
Sorry,  that was  Fabric.

Here is Forge with Ring of  Vision
![2022-02-20_10 31 23](https://user-images.githubusercontent.com/8809210/154853259-bcd98f36-ffa2-4559-817f-5474b267d382.png)

**Comment by kwpugh** [comment]
you likely  have a mod that is interfering  with the vanilla night vision.    Double  check by using vanilla night vision potion or via command to confirm.

**Comment by Ashtar084** [comment]
sorry for taking so long to respond.

 I will test today the return return to say.

thank you very much for your attention

**Comment by kwpugh** [comment]
No further info available, closing
