### ISSUE TITLE
[1.16.5] End gobber armor bug. 1.16.5

### ISSUE THREAD

**Issue by BigBoiSub** [kwpugh/gobber#128]
If you wear any piece of armor with any other armor that has durability, becomes indestructible too and if you equip end armor with armor that has low durability it will automatically repair it to full durability.

**Comment by kwpugh** [comment]
Oh wow,  just tried  and that is odd.  I will take a look.

**Comment by kwpugh** [comment]
I see what I did, so dumb.

**Comment by kwpugh** [comment]
Fixed in  2.3.54
