### ISSUE TITLE
[1.18.2] Can't use Gobber Ingots with silent gear blueprints

### ISSUE THREAD

**Issue by MasterTrollTNT** [kwpugh/gobber#129]
Hello everyone, I hope someone will be able to help me

Silent gear is suposed to take a lot of mods in his uses but when I try to make a helmet with a gobber ingot from Gobber 2 or Onyx from SimpleOres, it's not working.
Even when I try to see the partycularities of the ingots, it only works with Vanilla ingots

(PS : I'm in 1.18.2)

**Comment by kwpugh** [comment]
Did you install the Gobber datapack for Silent Gear?

**Comment by MasterTrollTNT** [comment]
No, I didn't know it needed a data pack
Where do I download it ?
and is ther a data pack for SimpleOres too ?

**Comment by kwpugh** [comment]
datapacks for my mods are in a Datapack channel on my discord.

**Comment by MasterTrollTNT** [comment]
Wich on it is ?

**Comment by MasterTrollTNT** [comment]
thank you

**Comment by MasterTrollTNT** [comment]
Ok
I'll tell you if it works
Do you know if I can put a datapack dirrectly on my Modpack or I have to put it manyaly everytime I create a new world ?

**Comment by kwpugh** [comment]
I put it in the /save/datapack folder

**Comment by MasterTrollTNT** [comment]
ok, thanks

**Comment by MasterTrollTNT** [comment]
Do I have to unzip the datapack ?

**Comment by MasterTrollTNT** [comment]
It Worked !!!
And it even activated the SimpleOres compatibility !

**Comment by kwpugh** [comment]
hmm, I just tried and it didn't work for me.  No recipes in the crafting table for gobber ingots.

**Comment by MasterTrollTNT** [comment]
weird
do you know if there's a curio compatibility datapack for gobber ?

**Comment by kwpugh** [comment]
maybe, but no of the ring powers would work in a slot because their is no support for curios in the mod.

**Comment by kwpugh** [comment]
did you have to do anything other than put the datapack in the /save/datapack folder?
