### ISSUE TITLE
Paxel does not break dirt and grass block any faster than by hand

### ISSUE THREAD

**Issue by Old-Man-D** [kwpugh/gobber#13]
I've just crafted the ring on haste and I went to test it and noticed that the shovel function of the paxel doesnt seem to work, it's the same speed as by hand.  I'm using a Paxel of the stars with torch mode on if that helps.

**Comment by kwpugh** [comment]
I see what I did.   I accidentally lowered the efficiency values when I was re-balancing the tools.   It will be fixed in the next update.

**Comment by Old-Man-D** [comment]
It was also missing the animation where the paxel swings, but only for grass and dirt.  Wood and stone both showed the animation of the paxel swinging
