### ISSUE TITLE
Wearing End Armor Suit in Creative disables flight ability

### ISSUE THREAD

**Issue by bloodconfetti** [kwpugh/Gobber#13]
Hello! When I switch into creative while wearing End Armor, I can no longer push double space to fly. I have to take the armor off, log out, log back in and then I can fly again.

Version: Gobber2-1.14.4-2.1.74
Forge Version: 28.0.41
Minecraft: 1.14.4

**Comment by kwpugh** [comment]
I will take a look at this.

**Comment by kwpugh** [comment]
Fixed in 1.14.4-2.1.79
