### ISSUE TITLE
Rings slots missing

### ISSUE THREAD

**Issue by pdrive** [kwpugh/gobber#132]
im using Gobber2-Forge-1.18.2-2.6.25 and curios-forge-1.18.2-5.0.7.0

somehow, not sure at what moment, the ring slots disappeared. ive tried forcing curios rings by editing the curios settings:
[[curiosSettings]]
  identifier = "ring"
  size = 2

but they dont fit. i cant place them in the new ring slots.  it appears they somehow lost the tag?
https://pixeldrain.com/u/2D5gE5cU

curios is working well with other mods. i can equip and use the backpack for example

**Comment by kwpugh** [comment]
Gobber no longer supports Curios.  No plans to add support in the future.

**Comment by pdrive** [comment]
oh okay. what about ring of repair? description also says it works with Curios. but it doesnt. i am able to equip it in the ring slots but it doesnt repair. only works while in inventory

**Comment by kwpugh** [comment]
there its no support for any ring in curios.
