### ISSUE TITLE
[1.18.2] Ring of the Farmer advancement is unstable

### ISSUE THREAD

**Issue by uhloin** [kwpugh/gobber#134]
I created Staff of the Harvest, Ring of the Farmer and Staff of the Farmer from them. As result advancement for Staff of the Harvest and Staff of the Farmer were marked but not for the Ring. May be it is because I did not close crafting interface after created ring and immediately crafted staff of the farmer. But later I created one more ring and advancement is appeared before I close craft. May be it is because I used crafting terminal from Applied Energetics 2, but now I cannot repeat it for vanilla craft table and second (success) attempt also was from AE2 terminal.

**Comment by kwpugh** [comment]
Turns out the text behind the Harvest Staff actually says Farmer.  Fixed for next update.
