### ISSUE TITLE
Ring of Repair (Standalone) does not repair items when placed in curios ring slot

### ISSUE THREAD

**Issue by hiddenyak** [kwpugh/gobber#136]
The Ring of Repair works as intended when the ring is in my inventory or hotbar, repairing items inside my inventory. When I place the Ring of Repair into the Curios Ring slot, it no longer repairs my items.

**Comment by kwpugh** [comment]
If you are using 1.18.2, Curios is not  supported.  I dropped support for Curios starting in 1.17.
