### ISSUE TITLE
Why does the ring of repair work when in an enderchest?

### ISSUE THREAD

**Issue by hiddenyak** [kwpugh/gobber#137]
Also, where is the repo for the code for the standalone ring of repair? as the standalone version does not work from an enderchest and is definitely using different code.

**Comment by kwpugh** [comment]
it is a fun little feature.  you  are the first to mention it.

**Comment by kwpugh** [comment]
Yes, the standalone version is slight different from the Gobbler ring, but  works mostly the same.
