### ISSUE TITLE
[1.18.2/1.19.0] gobberArmorHunger overtuned default value?

### ISSUE THREAD

**Issue by chad-steadman** [kwpugh/gobber#139]
Hello. I love this mod!

https://github.com/kwpugh/gobber/blob/9761f8ddfbd4c84fda3173fd4b97944fea6a96ec/src/main/java/com/kwpugh/gobber2/config/GobberConfigBuilder.java#L383

Is the `gobberArmorHunger` default value supposed to be `4` here? I noticed that Nether, End, and Dragon armor all have a value of 1.

**Comment by kwpugh** [comment]
fixed.
