### ISSUE TITLE
[1.18.2/1.19.0] Gobber armor has Wither protection

### ISSUE THREAD

**Issue by chad-steadman** [kwpugh/gobber#144]
The in-game item description for Gobber armor currently states the full set bonus only provides Poison protection, but currently Gobber armor also provides Wither protection.

#### Replication Steps:
1. In Survival with cheats enabled, equip full Gobber armor
2. Use `/effect` command to apply Wither effect to player
3. Observe Wither effect is immediately removed while full Gobber armor is equipped

#### Notes:
See PR #142 for more issue details and potential fix.

**Comment by kwpugh** [comment]
Fixed.
