### ISSUE TITLE
Ring of enderchest (standalone) keybind 

### ISSUE THREAD

**Issue by nheath** [kwpugh/gobber#147]
This mod would benefit from a dedicated keybind, for the ring of enderchest, allowing us to use a curios ring slot. It appears from the Gobber mod info, that this was an intended feature, but perhaps removed because of #33. Can this be re-enabled/fixed/added?

**Comment by kwpugh** [comment]
I  don't like the idea of key binds and curios, sorry.

**Comment by nheath** [comment]
The mod description says its supported, and should be updated so as not to be misleading

**Comment by kwpugh** [comment]
it doesn't say anything about ring slots

![Screen Shot 2022-06-25 at 8 40 10 AM](https://user-images.githubusercontent.com/8809210/175776082-1d82799b-13af-4f9b-8a24-8109616e6670.png)

**Comment by nheath** [comment]
Sorry, I should have been more clear, I was referring to the keybind that this issue was requesting be re-enabled.

![image](https://user-images.githubusercontent.com/1778613/175777892-717e2374-2309-4e99-8f16-8e1d6b95bd64.png)

**Comment by kwpugh** [comment]
ah.  I will update the table.  It was a feature in previous version but become far too problematic, so it was removed.
