### ISSUE TITLE
[1.18.2] Ring of Ascent not working

### ISSUE THREAD

**Issue by Maruhl** [kwpugh/gobber#148]
As the title says.

Dependencies:

+ Minecraft 1.18.2
+ Forge 40.1.48
+ Gobber2-Forge-1.18.2-2.6.28

**Comment by kwpugh** [comment]
Are you using in offhand?

**Comment by Maruhl** [comment]
No, normally selected in the item slot and right mouse button as always, or was the behavior changed?

**Comment by kwpugh** [comment]
yes, it changed

**Comment by kwpugh** [comment]
it should indicate so in the item's tool tips

**Comment by Maruhl** [comment]
Yes you are right, in the off-hand it works. Too bad, I found the previous behavior cooler :D

![grafik](https://user-images.githubusercontent.com/41585619/176253997-8dee615f-e23c-489c-b790-3bc6afa97397.png)

But the tooltip does not explicitly say that it has to be in the off-hand.

**Comment by Maruhl** [comment]
Yes, I know that, but then that's just the way it is. Can you not recognize the drop, and give the player an emergency buff so that he can bring himself to safety. Because of me 15 seconds levitate or so?

**Comment by Maruhl** [comment]
Or a configuration entry where you can switch between the new and old behaviors.

**Comment by kwpugh** [comment]
I've been playing with the offhand method in game and it is easy to get used to and simpler code.

**Comment by Maruhl** [comment]
Yes, I can imagine that. Thanks for the quick feedback. I will close the issue.

**Comment by kwpugh** [comment]
Are you using the latest version of Gobber?  
IT indicates offhand.

![Screen Shot 2022-06-28 at 1 25 45 PM](https://user-images.githubusercontent.com/8809210/176255664-f96c444a-b6fe-49e9-98df-51c15ed17197.png)

**Comment by Maruhl** [comment]
Oops my mistake, no this version is Gobber2-Forge-1.18.2-2.6.26 as this is on the server. But I explicitly tested the new one. I did not look at the tooltip of the new version.
