### ISSUE TITLE
[1.16.5] ores not generating

### ISSUE THREAD

**Issue by TeKett** [kwpugh/gobber#149]
I have no idea why since lucky blocks are still generating fine in all bioms, including modded.

**Comment by kwpugh** [comment]
which version?

**Comment by TeKett** [comment]
> which version?

Gobber2-Forge-1.16.5-2.3.54

**Comment by kwpugh** [comment]
can you post a copy of your latest.log?

**Comment by TeKett** [comment]
> can you post a copy of your latest.log?

How do you want it since it is 14 thousand lines

**Comment by kwpugh** [comment]
that's fine, just attach as a file.

**Comment by TeKett** [comment]
I think i found the issue looking through the log and configs. I was playing ragnamod 6, and for some reason your mod was in the pack, but also everything but lucky blocks seems to be disabled in every single location where it can be. Kinda strange imo.
[latest.log](https://github.com/kwpugh/gobber/files/9079037/latest.log)

**Comment by kwpugh** [comment]
are you seeing ores spawning now?

**Comment by kwpugh** [comment]
NoN more info provided, closing.
