### ISSUE TITLE
Suggestion/Note for Mine-And-Slash

### ISSUE THREAD

**Issue by Archesr** [kwpugh/gobber#15]
Hi, not sure where to post this, but to make the weapons armor and axe/paxels compatible with Mine-And_Slash
i have attached the code for the config\Mine and Slash\compatible_items file
Gobber files at the bottom of the file.

I added All Gobber items as rarity 3-5, Nether 4-5, End 5-5 (max rarity for best stats)
Not sure if you might recommend other options for rarity for balance.

[CompatibleItems.txt](https://github.com/kwpugh/gobber/files/3834420/CompatibleItems.txt)

**Comment by kwpugh** [comment]
Thank you.  I will take A look and then likely post a link on the Curseforge page.  I personally do not play Mine and Slash but I know some do.

**Comment by kwpugh** [comment]
Now handled by another mod:  https://github.com/AzureDoom/Mine-and-Slash-AutoCompat/tree/master/src/main/java/com/azure/azurecompat/util
