### ISSUE TITLE
Doubts 

### ISSUE THREAD

**Issue by Arnyet** [kwpugh/gobber#150]
I apologize, since English is not my native language, spelling horrors will exist.
I use Minecraft 1.18.2 - 1.19.x
 
I have some doubts (or bugs maybe) regarding the "Ring of Repair" mod

a) The ring does not repair items if you are not moving, if you stand still the repair does not activate, and it can go for hours without repairing anything at all.

b) Does it have compatibility with the "Curios Api" mod? supposedly it has an optional dependency, however when creating a slot for its placement, the ring stops repairing and does not work, is it a bug or does it not have compatibility? yes, if it has it (bug?), or no, will it have it in the future?

Thank you very much in advance, I apologize for the problems caused.

**Comment by kwpugh** [comment]
a) moving has nothing to do with whether it repairs or not.   It repairs one item at a time until it is fully repaired.  It will not repair an item currently being held.

b) 1.17+ no longer supports Curios API

**Comment by Arnyet** [comment]
I understand, thank you very much for your answer

**Comment by kwpugh** [comment]
was the issue that it wasn't repairing the item in your hand?  are the items in your inventory repairing or not?
