### ISSUE TITLE
[1.19] suggestion about status effects and config file

### ISSUE THREAD

**Issue by 48004800** [kwpugh/gobber#152]
The dark state effect added in version 1.19 cannot be removed by armor
Many mods add negative status effects, I guess it would be better to have a config file option for this.

By the way, in other mod dimensions players cannot fly with dragon armor. I want a powerful rig that can fly anytime, anywhere, and some people don't want the game to be too simple, so maybe it can also be solved in the way of configuration file options.

**Comment by kwpugh** [comment]
ok, I'm working on the following:

- add a check for Darkness effect on Dragon Armor and remove it if found
- add a config option to enable Dragon Armor flight in any dimension, disabled in config by default

**Comment by kwpugh** [comment]
![Screen Shot 2022-07-16 at 1 46 39 PM](https://user-images.githubusercontent.com/8809210/179368227-4515a623-0519-43ae-8b85-a32480c2dd9f.png)

**Comment by kwpugh** [comment]
Added to v2.7.5

**Comment by 48004800** [comment]
Maybe what I said before was not very clear, what I mean is that it can be modified in the config file to remove the status effects of other mods, or it may be that you think this will be too unbalanced. Anyway, thanks for your work. I am very happy with this new version.

**Comment by kwpugh** [comment]
If you are asking for the Dragon armor to remove negative status effects from OTHER mods, that I will not be doing.
