### ISSUE TITLE
Protector & Healer Blocks Provide X-ray

### ISSUE THREAD

**Issue by WenXin20** [kwpugh/gobber#16]
`Forge v28.1.90`
`Minecraft v1.14.4`
`Gobber 2 v2.1.114`

If the Protector & Healer blocks are placed next to another block, it allows you to see through the blocks behind it, allowing for X-ray vision of caves. They also can't be waterlogged.

**Comment by kwpugh** [comment]
I did notice that the bottom of the models issue through,  still looking into why.

**Comment by WenXin20** [comment]
I found a similar issue at Glitchfiend/BiomesOPlenty#1517 that may help solve this problem.

**Comment by kwpugh** [comment]
Fixed in 1.15.1 version.  I may look at older versions as well.
