### ISSUE TITLE
Block Protector Crash w/ Rediscovered's Scarecrow

### ISSUE THREAD

**Issue by WenXin20** [kwpugh/gobber#17]
`Minecraft v1.14.4`
`Forge v28.1.90`
`Gobber 2 v2.1.114`
[`Rediscovered v1.0.0`](https://www.curseforge.com/minecraft/mc-mods/rediscovered)

After right-clicking the block protector, I got this crash because a scarecrow from the Rediscovered mod was placed nearby.
[Crash Report](https://gist.github.com/WenXin20/8332402634588a685c7097f0623c25b8)

**Comment by kwpugh** [comment]
Which scarecrow were you using when it crashed.  I have tried a few with the protector and no crash.

**Comment by WenXin20** [comment]
Isn't there only one scarecrow item from Rediscovered?
 I won't be able to check this weekend, my laptop isn't with me.

**Comment by kwpugh** [comment]
Sorry, I was looking at the Scarecrow mod, not Rediscovered.   Looking at it now.

**Comment by kwpugh** [comment]
Fixed in latest release.
