### ISSUE TITLE
Nether and End ore issue

### ISSUE THREAD

**Issue by kcjosh** [kwpugh/gobber#18]
Ores in the Nether and End don't drop anything. Ores in the overworld drop correctly. I am on Forge version 28.1.90 and mod version 2.1.114.

**Comment by kwpugh** [comment]
Are you using the correct tool with a sufficient harvest level?

- Gobber Ore requires harvest level 3+ (diamond pickaxe)
- Nether Gobber Ore requires harvest level 4+ (Gobber Pickaxe)
- End Gobber Ore requires harvest level 5+ (Nether Gobber Pickaxe)

**Comment by kcjosh** [comment]
This was my issue. Didn't realize it scaled up like that and it breaks easily using a diamond pick but doesn't drop anything. Overall enjoying the mod, thanks.

**Comment by kwpugh** [comment]
Great.  Thanks.
