### ISSUE TITLE
[1.14.4] Ring of the farmer hard locks the server - conflict with Wild Nature grass.

### ISSUE THREAD

**Issue by ProsperCraft** [kwpugh/gobber#19]
![bd8fb2f07122bbc48840bfa15de7dc68](https://user-images.githubusercontent.com/4427684/70687523-acd66980-1c6c-11ea-8e32-d0c05d79afd4.png)

Gobber2-1.14.4-2.1.115
wildnature-2.1.0
forge-1.14.4-28.1.104

**Comment by kwpugh** [comment]
Was there a crash report at all?

**Comment by kwpugh** [comment]
The author of Wild Nature does share its source code online, so I can look at it to debug.   I will ask.

**Comment by kwpugh** [comment]
Also, can you describe what was being done when it locked up?

**Comment by kwpugh** [comment]
Without seeing the AU goes source code, I suspect I know what the problems is.   The item scans for blocks that implement forge’s IGrowable interface and executes the Grow method on them.   I found in my early testing that some vanilla blocks go CRAZY with that (e.g. grass, rose bushes, etc) so I explicitly excluded them.   If this mod adds new grasses or bushes based on vanilla classes, that may be the problem.

**Comment by ProsperCraft** [comment]
It doesn't crash, it hard locks and is unresponsive.

**Comment by kwpugh** [comment]
This appears to be fixed.   If not, re-open.
