### ISSUE TITLE
Hammer

### ISSUE THREAD

**Issue by TookUrSweetRoll** [kwpugh/Gobber#2]
Gobber hammer breaks bedrock if it is adjacent to stone being struck. Does not drop item. Using v32.

Side note: Noticed some lag (block breaking, lighting) after using Ring of the Miner.

**Comment by kwpugh** [comment]
Added check to exclude blocks that have the "witherImmune" block tag from the breaking effect.   This include BedRock.

Included in v35.

**Comment by kwpugh** [comment]
Please confirm with v35 when you get a chance.

**Comment by kwpugh** [comment]
Relating to the Miner lag, make use you are using latest Forge, was an issue in earlier version.

**Comment by TookUrSweetRoll** [comment]
Resolved with v35. Thank you.

**Comment by kwpugh** [comment]
FYI, in v36 the Ring of the Miner will have a new feature.   Sneak right-click will simply remove the blocks rather than breaking.  I got tired of filling my inventory with cobble.  ;)

**Comment by TookUrSweetRoll** [comment]
Very nice. No more lava bucket.
