### ISSUE TITLE
using BlockProtector causes crash

### ISSUE THREAD

**Issue by zadzial** [kwpugh/gobber#2]
First: really liking this mod! Sadly, having just laid down the hostile mob protection thing, MC crashed and now I can't load the world (others are fine, just the one I used the device in). I tried to delete it manually using an NBT editor, but I can't access the chunk - it too crashes. Making sure I was up to date with forge hasn't helped. 
I can get the world back by backup, but I thought I should let you know about the issue.

[crash-2019-09-03_22.06.50-server.txt](https://github.com/kwpugh/gobber/files/3569341/crash-2019-09-03_22.06.50-server.txt)

**Comment by kwpugh** [comment]
I see I need to exclude armor stands from the entity scan.   I will take a look after work tonight, likely an easy fix.

**Comment by kwpugh** [comment]
Fixed in version 89 of Gobber.   You can updated the mod and should be able to rejoin old world, if you haven't already moved on.

Fix: added exclusion for ArmorStandEntity to AABB scan results before killing entity.

**Comment by zadzial** [comment]
Thankyou!
