### ISSUE TITLE
[1.15.2] Mod does not load from defaultconfig path

### ISSUE THREAD

**Issue by realTIMematrix** [kwpugh/gobber#27]
Hi,

I'm using:

Minecraft: 1.15.2
Forge: 31.0.16
Gobber2: 2.2.36

I recognized that you create two different .toml files. gobber-general.toml at start-up and gobber2-server.toml after creating a new world. When you move both files to the defaultconfig folder (which forge creates) and delete the file in the config folder and the savegame then after the next start only the gobber2-server.toml will be loaded from the default config path, but not the other one. this will be new created instead loading the file from defaultconfig. This is a problem for modpack developers who define the configuration and place all the configs in the defaultconfig folder.

`[03Feb2020 19:43:40.070] [modloading-worker-2/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Username\Documents\Minecraft\Modpacks\1.15.2\Test Pack\config\gobber-general.toml is not correct. Correcting`

`[03Feb2020 19:44:09.610] [Server thread/INFO] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Loading default config file from path C:\Users\Username\Documents\Minecraft\Modpacks\1.15.2\Test Pack\defaultconfigs\gobber2-server.toml`

**Comment by kwpugh** [comment]
Fixed in latest release
