### ISSUE TITLE
[1.15.2] Conflict with Mending

### ISSUE THREAD

**Issue by Mikeliro** [kwpugh/gobber#29]
Items with the 'Mending' enchantment do not receive XP when I have one of the rings (Ring of Repair or 
Ring of Attraction) in my inventory.

**Comment by kwpugh** [comment]
The Ring of Repair does not work with the Mending Enchant.  I may look into changing that, but not sure.

**Comment by MichaelLimaRodrigues** [comment]
And the conflict with the Ring of Attraction?

**Comment by kwpugh** [comment]
It pull in xp orbs as well as items.   I'll check on that part.

**Comment by kwpugh** [comment]
Check the new release.  I believe I fixed the problem caused by the Ring of Attraction.

**Comment by kwpugh** [comment]
Did the issue with the Ring of Attraction clear up with the new release?

**Comment by Mikeliro** [comment]
Yes, it is working normally.
