### ISSUE TITLE
Sneaking in Gobber Armor

### ISSUE THREAD

**Issue by TookUrSweetRoll** [kwpugh/Gobber#3]
Wearing the armor (any) disables moving while sneaking. Unequipping and relog clears it.

Using v34

**Comment by kwpugh** [comment]
Hi,

Thanks for reporting.

Was this in single player, server, or both?

**Comment by kwpugh** [comment]
I made an adjustment to the base step height on armor removal.  I do not get the sneak problem.   Please check v35 to see if you still have the problem and let me know.

**Comment by TookUrSweetRoll** [comment]
This was in single player only. Resolved with v35. Thank you.

**Comment by TookUrSweetRoll** [comment]
Now cannot walk over carpet, or from farmland to full block.

**Comment by kwpugh** [comment]
Ok, I think I got it.

Can you try this version and let me know?

https://gofile.io/?c=rU8YdW

**Comment by TookUrSweetRoll** [comment]
Fixed with v37

**Comment by kwpugh** [comment]
Great.  Thanks for reporting and being patience with the fixes.

**Comment by kwpugh** [comment]
The official v37 update is on Curseforge, with a few our tweaks.
