### ISSUE TITLE
Ring of Attraction causes crash

### ISSUE THREAD

**Issue by PikachuPlaysSKY** [kwpugh/gobber#3]
So I've been using this mod for a while now and I've finally been able to build a ring of attration. I turned it on then cycled through the ranges, got to the max and then it crashed on me. I've been trying to get back into the world but it now keeps crashing my game. I can't load into that world anymore either.

[crash-2019-09-14_12.23.32-server.txt](https://github.com/kwpugh/gobber/files/3612924/crash-2019-09-14_12.23.32-server.txt)

MC 1.14.4
Forge 28.0.107
Gobber 2.1.92

**Comment by kwpugh** [comment]
Update to latest Forge 28.1.0+ and let me know if still a problem.

**Comment by PikachuPlaysSKY** [comment]
working fine now, thanks
