### ISSUE TITLE
[1.15.2] Staff and Paxel of the Stars torches should not drop

### ISSUE THREAD

**Issue by kwpugh** [kwpugh/gobber#30]
1. Add custom Gobber torch that does not drop itself
2. Gobber torch has no recipe
3. Gobber torch only used by Staff/Paxel of the Stars

**Comment by Giintaras** [comment]
Yeah.. that's the only reason I refrain from using those items, too op. Same as creative flight armour.. OP.

**Comment by NoDreamsRemain** [comment]
Maybe Nerf the Dragon Armor. I think the creative has temporary flight and then when it ends, you can't fly untill it recharges. (if it ends when you're flying, it gives slow falling so you can't just go down. i know when we have the complete set, we dont take damage, but if we're in the end and the flight ends it may complicate where you can land wihout going to the void and lose all of your items.)

**Comment by NoDreamsRemain** [comment]
Also, ikr that is hard to get that armor so there's a point to have creative y'know, but its too OP

**Comment by NoDreamsRemain** [comment]
> 1. Add custom Gobber torch that does not drop itself
> 2. Gobber torch has no recipe
> 3. Gobber torch only used by Staff/Paxel of the Stars

.

**Comment by kwpugh** [comment]
Decided against doing this.
