### ISSUE TITLE
[1.15.2-2.2.60] Gobber glass voids anything that lands on placed Gobber glass

### ISSUE THREAD

**Issue by shortybsd** [kwpugh/gobber#32]
**Forge:** 31.1.18
**Gobber2:** 1.15.2-2.2.60

When breaking Gobber glass, if it falls down and hits an already placed Gobber glass below it, it voids the dropped item. If you throw any item at the placed glass it voids it. Not for sure if this was intended but insanely dangerous!

**Comment by kwpugh** [comment]
I see what I did.  ON collision, it was checking for non-player entity and then causing damage.  I didn't know blocks could take damage that way.   Fixing now.

**Comment by kwpugh** [comment]
Will be fixed in 2.2.61
