### ISSUE TITLE
[1.15.2] Ring of enderchest

### ISSUE THREAD

**Issue by MasterSloth1** [kwpugh/gobber#33]
ring of ender chest corrupts my player data when ever i pull it out of jei giving me a netty io error resetting player data fixs this issue
forge-31.1.19
Gobber2-1.15.2-2.2.63.jar

**Comment by MasterSloth1** [comment]
also the Defender block and the looter block dont drop them selfs when broken

**Comment by ProsperCraft** [comment]
Verified-
https://gist.github.com/ProsperCraft/7d76f8b793c7644838e9d56280e1a22f

**Comment by kwpugh** [comment]
@MasterSloth1 by "pull it out of jet" you mean in creative mode?

**Comment by ProsperCraft** [comment]
Mair had crafted it before the update to the recent version, and had it in his bag, when he pulled it out after the update, he instantly could not log in, and gets kicked on relog.

**Comment by kwpugh** [comment]
which bag?

**Comment by MasterSloth1** [comment]
correct i was in creative mode and i pressed 4 while hovering over it

**Comment by ProsperCraft** [comment]
Alchemical bag

**Comment by kwpugh** [comment]
Which mod is that from?

**Comment by kwpugh** [comment]
fixed in v64 and the standalone ring of enderchest mods.   Keybind code has been disabled.

**Comment by MasterSloth1** [comment]
is the bag relevant? i didnt have the bag, i plucked it from jei straight into my inventory.

**Comment by ProsperCraft** [comment]
Resolved, you can close.
