### ISSUE TITLE
config for ring of attractions

### ISSUE THREAD

**Issue by frakier** [kwpugh/gobber#38]
Where is the config file. I'm having problems where when I change the range it only shows 0. It can be turned off and on. but the only way to get the range working again is to close minecraft and log back in. Wanted to delete the config and see if that helps but cannot find it. Normally I would look at a source code before asking but that is not a option here.
edit: or outside of the config how is the status saved.

**Comment by kwpugh** [comment]
Which version are you using?

**Comment by kwpugh** [comment]
The range is read from/written to the NBT of the ring itself, no config.

**Comment by kwpugh** [comment]
Btw: did you happen to remap you Sneak function to something other than the Shift key?

**Comment by frakier** [comment]
forge-1.14.4-28.2.0
RingOfAttraction-1.14.4-1.0.20

Nope still using Shift Key.

If I throw the ring away and make another that would by the equivalent of getting rid of the config? I'll try that.. if if does not work that way I'm not loosing anything.

I already had everyone dump their inventory and deleted the playerdata files on the server.

Let me see if I have any mod that interacts with the NBT outside of normal operations.
just the obvious one nbttooltips-1.0.jar and that us just read only access.

**Comment by frakier** [comment]
OK disk usage was at 89% got it down to 57% [got rid some old outdated mod packs] I'll try it out and let you know. Closing for now will reopen if it persists.

**Comment by frakier** [comment]
The problem is still there but it has to be interference from another mob, checked the NBT data using NBTExplorer and do not see anything wrong looked at tit working and when it was not working I checked the NBT data again, nothing obvious. If I can figure out which mod is causing the problem I will report back. Thanks for the help.
