### ISSUE TITLE
Paxel glitch

### ISSUE THREAD

**Issue by lycanthrope7** [kwpugh/gobber#39]
Hey kwpugh, let me start by saying how much I love Gobber, and really appreciate your work. I'm having an issue with the Paxel's glitching out and not being able to break gravel or sand sometimes. I'll go to dig out a block, and that block will disappear and the particle effect will show, but the moment I dig another block of the same type, the original one reappears. Neither block is added to my inventory.

I'm running Minecraft 1.15.2, Forge 31.1.0 and Gobber 2.2.77

Admittedly I have 38 other mods installed, and Gobber is one of the most recent additions, so it could be that it's not playing nice with something else. If you need a list of the other mods, let me know.

**Comment by kwpugh** [comment]
Hello,

Thank you for reporting.

A couple of things:

- you might want to move to a more recent version of Forge, 31.1.41 is the latest.  There has been a lot work on the rendering engine in Forge over recent months.
- Can you post on logfile from a session when you experienced the glitch.   Use Gist or hastebin or something
- Can you post a list of the other 38 mods you are playing with?

regards.

**Comment by kwpugh** [comment]
I have tried multiple paxels on both sand and gravel and I cannot replicate the glitch.   What you are describing sounds a lot like block lag, but I would need to see a logfile to be sure.

**Comment by kwpugh** [comment]
Cannot reproduce.
