### ISSUE TITLE
[1.14.4] Ring of Attraction - activation causes crash

### ISSUE THREAD

**Issue by bauerwilhelm** [kwpugh/gobber#40]
When I have the ring in my inventory nothing happens, I can even change the range. But when I activate it via right click it causes a crash to desktop.

[crash-2020-04-19_23.12.01-server.txt](https://github.com/kwpugh/gobber/files/4500308/crash-2020-04-19_23.12.01-server.txt)

**Comment by kwpugh** [comment]
Weird that this hasn't shown up in last 4 months.   I'll take a look, but 1.14.4 is low on the list at this point, very different code basin 1.15.2 and 1.16.

**Comment by bauerwilhelm** [comment]
Okay, doesn't matter really. I use notenoughbuttons then, when I need to be magnetic :D
