### ISSUE TITLE
Please Restore all 1.12.2 Versions

### ISSUE THREAD

**Issue by CrankySupertoon** [kwpugh/gobber#43]
Not just for Historical Purposes but legacy modpacks like mine are broken. One I knew of one featured Gobber heavily and now they can’t update the pack since curse will reject it since the file is archived.

**Comment by kwpugh** [comment]
I removed it because it is no longer supported.  I put it back up for now, however, if I get more requests about updating it, it will come done permanently.

**Comment by CrankySupertoon** [comment]
Thank you 🙏 

Also screw the idiots who said that. Maybe start bugging ender io to port instead of a mod to backport

**Comment by CrankySupertoon** [comment]
What was the 1.12 Version Licensed under having trouble finding the source for that. Was that the MIT one and the new one is LGPL or something like that

**Comment by kwpugh** [comment]
I completely re-wrote Gobber for 1.14+, the old code base of 1.12 is a mess, and I'm not going to touch it.  lol
