### ISSUE TITLE
Request: Config Option to Disable Items

### ISSUE THREAD

**Issue by redlettertech** [kwpugh/gobber#44]
I'd love to see options added to the config file to disable certain items (such as the area defense blocks).

**Comment by kwpugh** [comment]
In 1.15+, Forge does not recommend disabling the registry of items via config.   Recipes can be disabled via data packs if you doo not wish the blocks to be crafted.  At present, I do not know how to disable recipes in code.

**Comment by kwpugh** [comment]
Recipes can be disabled via data packs or MineTweaker if desired.
