### ISSUE TITLE
Ring of Attraction - Feature Request

### ISSUE THREAD

**Issue by TookUrSweetRoll** [kwpugh/gobber#45]
Would it be possible to add a blacklist filter?

**Comment by kwpugh** [comment]
What are some examples of what would be on a black list?

**Comment by TookUrSweetRoll** [comment]
Like this:
[https://ftb.gamepedia.com/Item_Filter_(Extra_Utilities_2)](url)

So it will not pick up things from my farms (cactus, bamboo, etc.)

**Comment by kwpugh** [comment]
A magnet "de-magntizer" has proven better in these situations.   Here is a Forge example.  https://www.curseforge.com/minecraft/mc-mods/demagnetize.   I will look into such a feature.

**Comment by TookUrSweetRoll** [comment]
That would work. Thank you.

**Comment by kwpugh** [comment]
I got a simple method that detects if a particular block (e.g. Redstone Block) is in scan range and if so, stops the attraction process.  Once out of range of the particular block, attraction resumes.   Will that be workable?

**Comment by kwpugh** [comment]
Also, the author of Demagnetize plans to updated for Forge, but doesn't have a date when that might happen.

**Comment by TookUrSweetRoll** [comment]
Yes that is good. One suggestion, could you make it a Gobber block? Or maybe craft a Gobber block with another item to create a specific block called the Demagnetizer? 

Reasoning: if a build has a redstone block in it that I DO want to pick up from, it would break it.

**Comment by kwpugh** [comment]
I really don't want to add another block just for this purpose.   I will use a coal block, since that doesn't get used for much more than a furnace fuel.

**Comment by TookUrSweetRoll** [comment]
Sounds good. Thank you.

**Comment by kwpugh** [comment]
Added in the latest releases of Gobber and standalone Ring of Attraction
