### ISSUE TITLE
LGPL or MIT?

### ISSUE THREAD

**Issue by CrankySupertoon** [kwpugh/gobber#46]
CurseForge says MIT and Repo says LGPL which is the correct license. I know these two are basically identical but just curious anyways. Thanks :)

**Comment by kwpugh** [comment]
MIT and the source are now added as additional files.   If you create a fork on 1.12.2, don't use Gobber name.

**Comment by CrankySupertoon** [comment]
Care upload the actual source so the mappings aren’t screwed with

**Comment by kwpugh** [comment]
Try that.

**Comment by kwpugh** [comment]
Should approve shortly

**Comment by kwpugh** [comment]
Oh, and the 1.15.2 textures are not to be used in old versions or forks.
