### ISSUE TITLE
Glob seeds do not provide an effective source of glob

### ISSUE THREAD

**Issue by ImPickleJeff** [kwpugh/gobber#5]
When harvesting seeds, you get a glob, but you don't get any seeds back. To make seeds, you need 8 glob. So to get 1 glob by a seed, you need to already have 8, making the seeds useless. Please fix this so when harvesting a seed, you get some seeds back as well as some glob.

**Comment by kwpugh** [comment]
Hello,

I have tried both ways going back to the 1.12.2 version and have found that with seed drops it becomes way too easy to obtain lots of globs.   The Gobber seeds are meant as an alternative to mining for Gobber in a more sustainable manner, not necessarily as fast way, especially servers where areas get mined out.  

Given the ease with which one can build a Ring of the Farmer, getting a good amount of Globettes for making Gobber is a very simple manner.

Sorry, working as designed.

Regards.

**Comment by ImPickleJeff** [comment]
Thanks for the response, I see now what you were intending and completely
understand. Thank you for informing me of this, and apologies for the
comment.

Kind regards, the29987.
