### ISSUE TITLE
[1.14.3] Toggle does not keep night vision from running out.

### ISSUE THREAD

**Issue by ProsperCraft** [kwpugh/Gobber#5]
As of Gobber2-1.14.3-2.1.40 the new night vision toggle on the pick gives you night vision initially but still needs to be refreshed by right clicking.

**Comment by kwpugh** [comment]
Yes, that was intended.   The toggle is just to turn the "ability" on and off.   People were right-clicking and getting night vision when they didn't want it.

If people want continuous night vision, that is what the Ring of Vision is design to do.

**Comment by kwpugh** [comment]
The new sneak toggle does not change the right-click functionality, it allows the player to enable-disable it.

Sorry for the confusion.

**Comment by ProsperCraft** [comment]
Very good, thank you.
