### ISSUE TITLE
[1.16.x] Gobber Foo - Feature Request

### ISSUE THREAD

**Issue by TookUrSweetRoll** [kwpugh/gobber#50]
1. Use Foo to make torches, with matching color (Foo = blue etc.). Not the light itself, just the torch.

2. Tiered quantity increase?

3. Would a progressive radius be too much (or too hard)? Foo + 2, Nether + 4, End +8

**Comment by kwpugh** [comment]
Possibility in 1.16, not sure.

**Comment by kwpugh** [comment]
Expansion of Foo items, like torches are not something I plan to pursue
