### ISSUE TITLE
Ring of the Miner

### ISSUE THREAD

**Issue by JillSwift** [kwpugh/gobber#52]
Add Nether Bricks & Nether Brick Fence to "do not ~~eat~~ mine/destroy" list, pretty please. 😸

**Comment by kwpugh** [comment]
I'll take a looks

**Comment by kwpugh** [comment]
Fixed in standalone Ring of Miner.  Will do Gobber next.

**Comment by kwpugh** [comment]
Fixed Ring of Miner in Gobber as well.
