### ISSUE TITLE
[1.15.2] Ring of the Pyro conflict with MineColonies Mod

### ISSUE THREAD

**Issue by Sharalith321** [kwpugh/gobber#53]
Hey there, love ur Mod but i have a problem with Minecolonies the Ring kills all my citizens
its a great tool to get rid of the OP Pirates but yeah if u kill ur People with it its useless.

**Comment by kwpugh** [comment]
Ok.  Fixed the Ring of Pyro so it doesn't affect Citizens by specifically excluding entities inherited from VillagerEntity and AgeableEntity.   HOWEVER, Mercenary are a different story, since they are inherited from CreatureEntity, like raiders, illagers, etc. in Minecraft.  I will need to do some research on how I might excludes those.

**Comment by Sharalith321** [comment]
Thx a lot =D

**Comment by Raycoms** [comment]
Minecolonies Dev here: Both mercenaries and Minecolonies citizens use: EntityClassification.CREATURE which should be a save bet to exclude from the ring (Bats, pandas, wolfs, lamas etc are all CREATURE too, while illagers etc should be MONSTER)

**Comment by kwpugh** [comment]
Oh, I did not know that even existed.   I was checking entities with "instanceof" against the entities class.   I will check it out.

**Comment by kwpugh** [comment]
@Raycoms looks like EntityClassification is only used for populating biomes and in some AI tasks.  Any idea how to check the classification when I have the MobEntity object?

**Comment by Raycoms** [comment]
You get the EntityType of the mod and from the entityType you get the classification.

**Comment by kwpugh** [comment]
ok.  I think I got it.    One thing, I'm trying to test on a Merc by spawning from an egg, but it disappears instantly.   Is there a command to spawn the various entities of the mod?

**Comment by kwpugh** [comment]
Fixed the issue in v97
