### ISSUE TITLE
[1.15.2] Paxel of the stars torch placement bugs.

### ISSUE THREAD

**Issue by K41eb** [kwpugh/gobber#54]
Minecraft - v1.15.2
Forge - v31.2.0
Gobber 2 - v2.2.97

I was playing around in creative with [your mod](https://www.curseforge.com/minecraft/mc-mods/gobber) and I accidentally placed a torch on top of rails and it placed it in the air on the block above. I also tried on the wooden "pillar" of this mineshaft and same problem, the torch is floating in the air.

[Screenshot](https://imgur.com/t4mqdBq)

Now if it matter I have the [Torch Slabs Mod](https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod) which allows me to put torches on the side of slabs, stairs, etc ... but note that regular torches work just fine: I cannot place them like the Paxel of the Stars tool does.

I also observed that you can place torches on object you otherzise can't with a regular torch like grass and plants.

Items that usually do not support torches but "do" (including floating torch isntances) for the Paxel of stars:
- rails
- fences
- vines
- grass
- leaves
- mushrooms
- flowers
- spider webs

It does not place torches on fruits or living entities. It does not attempt to place torches under water whereas vanilla torches are placed and quickly removed by the water (I like your mod's behavior better, I'm just throwing the info in there in case it help with the debugging).

I have never modded but it looks like the condition on the target block is not right for torch placement.

**Comment by kwpugh** [comment]
Fixed in 1.16.4 and going forward.   Will issue an update for 1.15.2 as well.

**Comment by kwpugh** [comment]
Mostly fixed in 1.15.2 update.   does not work placing on top of fence post.
