### ISSUE TITLE
Ring of Attraction range always displays zero in the item's lore

### ISSUE THREAD

**Issue by ThatPreston** [kwpugh/gobber#56]
You can cycle through the different ranges on the Ring of Attraction and it works great. But when you hover over the item in your inventory, it always says the range is zero.
![Capture](https://user-images.githubusercontent.com/52404366/84305238-54026380-ab1f-11ea-8496-35bbeab6eb14.PNG)

**Comment by kwpugh** [comment]
You must have had one when I changed the cycle of the ring.   It no longer has a value of zero.   Try pulling a new one out of creative or craft a new one, it should not have the problem.
