### ISSUE TITLE
[1.15.2] Disable Standard Drop Mode

### ISSUE THREAD

**Issue by TheUntamed** [kwpugh/gobber#57]
Could you add an option to completely disable the Standard Drop Mode so that the No Drop Mode is the only available mode?

**Comment by kwpugh** [comment]
What are you referring to?

**Comment by TheUntamed** [comment]
oh, sry. Didn't saw that this is a general github.
I'm referring to the Ring of the Miner [FORGE] mod and item.

**Comment by kwpugh** [comment]
why?

**Comment by TheUntamed** [comment]
Cause I want it to be able to destroy blocks without the benefit to get the drops.

**Comment by kwpugh** [comment]
You can already do that with current settings.

**Comment by TheUntamed** [comment]
Right now it is only possible to switch between both modes by sneaking.

**Comment by kwpugh** [comment]
Working as designed, no change expected.
