### ISSUE TITLE
[1.15.2] [Bug] Dragon Armor - Permanent Slowness Bug

### ISSUE THREAD

**Issue by mr-poyo** [kwpugh/gobber#58]
**Version:** Gobber2-1.15.2-2.2.102.jar
**Forge:** 31.2.30

When wearing dragon armor and given the slowness effect, the player's speed is permanently slowed until death. Removing the armor doesn't restore player's speed to normal. To my knowledge, the only way to restore speed is death, or refreshing the slowness debuff (at a different amplifier) without the armor on. 

Steps to reproduce:
1) Wear full dragon armor
2) Run this command to give yourself slowness `/summon minecraft:area_effect_cloud ~ ~ ~ {Duration:20,Effects:[{Id:2b,Amplifier:2b,Duration:200}]}`
3) Try walking around with or without dragon armor

If it's any help code-wise, End Armor seems to work fine.

Not too sure about code but maybe boolean check on line 36 is missing "is"? 
`if(!player.getPersistentData().contains("wearingFullDragonArmor"))player.getPersistentData().putBoolean("wearingFullDragonArmor", false);`
`boolean iswearingFullDragonArmor`

**Comment by kwpugh** [comment]
I will take a look as I am updating to 1.16.1

**Comment by kwpugh** [comment]
No longer present in 1.16.4.
