### ISSUE TITLE
[1.15.2] Ring of Ascent doesn't activate when Ring of Curing is in player inventory

### ISSUE THREAD

**Issue by jengendler** [kwpugh/gobber#59]
Minecraft version 1.15.2
Forge version 31.2.30
Mod version 2.2.102

I noticed I wasn't able to activate the Ring of Ascent in my world, so I tested this in a brand new world with only the Gobber 2 mod installed. I found that when I have the Ring of Curing in my inventory, I cannot activate the Ring of Ascent. Otherwise, the ring works as expected when I do not have the Curing ring in my inventory. Not sure if this is by design, but I would like to be able to use both simultaneously.

Thanks for making one of my all-time favorite mods! :)

**Comment by kwpugh** [comment]
Hello,

That was a trade-off I made in design.

The ring of ascent uses the Levitation potion effect and the Ring of Curing negates that potion.   Reason being, I wanted the ring of curing to negate it for use in fighting Shulkers in the end.

When I am updating Gobber to 1.16.1, I will investigate if there is a way to only negate the effect IF the player is in the end, but not in other dimensions, no promises.

I am glad you are enjoying the mod.

Regards.

**Comment by jengendler** [comment]
Ahh, that makes sense. Thanks for the info!

**Comment by kwpugh** [comment]
Working as designed.
