### ISSUE TITLE
[SUGGESTION] End Glass fix

### ISSUE THREAD

**Issue by Nachtflame** [kwpugh/gobber#6]
Not sure what issue was preventing it being "Not wtiher proof yet", but the tag <minecraft:wither_immune> works (I've tested), you'd just need to up the blast resistance of the block to withstand his initial explosion, and the blasts of his attacks. :)

**Comment by kwpugh** [comment]
I wasn’t aware of that tag.  I will take a look.

Thank you for pointing it out.

**Comment by kwpugh** [comment]
Either proof glass is not going to be a feature.
