### ISSUE TITLE
[1.14.3] NIght Vision ring no longer gives night vision.

### ISSUE THREAD

**Issue by ProsperCraft** [kwpugh/Gobber#6]
Video here- https://gyazo.com/85b6e070688089129fae2b5ded2890ba

**Comment by kwpugh** [comment]
I will take a look after work.

**Comment by kwpugh** [comment]
New version is up on CurseForge with the fix.   I made a "fat finger" mistake last night that my IDE did not catch.  I tested it and all is good.   Let me know if otherwise.

**Comment by kwpugh** [comment]
Seems to be fixed
