### ISSUE TITLE
[1.17.1] [Suggestion] Ring of Attraction Override Block

### ISSUE THREAD

**Issue by 4Magma** [kwpugh/gobber#60]
i use the ring of attraction mod, but the coal block as demagnetice 
is a bad solution:
- if block is in range of ring, attraction is disabled
- if block is again out of range, all items in range 
  are attracted
- to protect a area i must place coal blocks at 
  any corner, but i also can't use attraction nearby
  
suggestion: 
- new block to prevent attraction in a custom region 
- recipe: ring of attraction + any block
  (used block defines appearance, ring not used)
- gui allows to define region from 0..3 in any direction
  (this way max region is 7x7x7 with block in center)
- protected blocks are put on a list which ring must check each time
- ring should only protect unattracted items, allready attracted 
  items which cross region should stay attracted by ring

greetings
Martin Urban

**Comment by kwpugh** [comment]
May look at adding this feature in current release.

**Comment by kwpugh** [comment]
this is a feature I'm not going to be pursuing
