### ISSUE TITLE
[1.16.1] Ring of Repair (Forge) standalone

### ISSUE THREAD

**Issue by Dragnier** [kwpugh/gobber#63]
Not working when on Curios ring slot. Simply does not repair until moved back to the regular inventory.

**Comment by kwpugh** [comment]
Curios is not re-enabled yet for the 1.16 versions of the mod.   Will likely be fixed in 1.16.3.

**Comment by kwpugh** [comment]
All aspects of Curio are removed for now, so players cannot put the ring into a Curio slot.
