### ISSUE TITLE
[1.12.2] Can't harvest Gobber seeds with Quark installed

### ISSUE THREAD

**Issue by apocalypse3000** [kwpugh/gobber#64]
I know, 1.12.2 is no longer supported, but this is serious problem that should be fixed. It works fine without Quark installed, but when I install Quark, I cannot harvest any Gobber seeds. Of course I can break a plant, but it doesn't drop any seeds. Pam's Harvestcraft seeds and other seeds work fine.
Any chance for this to be fixed?

Forge 14.23.5.2847
Gobber 1.1.207
Quark 1.6-179
AutoRegLib 1.3-32

**Comment by kwpugh** [comment]
Can you be more specific about "can't harvest"?   When you break the mature plant, does a crop drop?

**Comment by apocalypse3000** [comment]
Quark has a feature to harvest grown crops by right click, but it doesn't work, even with a hoe (another Quark feature). When I break a mature plant, seed won't drop as well.

**Comment by kwpugh** [comment]
Since it works without Quark, I do not consider this a critical bug, also given that 1.12.2 is out of support.   Time to consider moving on to a more recent version of Forge.  Sorry.
