### ISSUE TITLE
[SUGGESTION] Curios support

### ISSUE THREAD

**Issue by MasterSloth1** [kwpugh/gobber#7]
could u add support for curios on your rings please 😄 
this mod
![image](https://user-images.githubusercontent.com/34207969/66249485-e7191b80-e790-11e9-9765-87666f51e193.png)

**Comment by Knito58** [comment]
Maybe expandable with a ring tool: Normal, Nether and End ring tool made with Gloo of corresponding material. And opening 1, 2 or 3 slots or even 2,4 and 6 slots for that great rings.

**Comment by Knito58** [comment]
Just made a datapack for my "Tester" world: The ring of attraction works perfectly while being in a Curios slot. At least in single player survival.

**Comment by MasterSloth1** [comment]
could u send me that data pack lol im new to it and want to learn more

**Comment by Knito58** [comment]
@MasterSloth1: Read the curios front page as the datapack is not everything to be done. And mine is derped as I made it for the angelring which does not work in curios. The hint seems to be broken but it works (for me) with the ring of attraction.
https://www.dropbox.com/s/sn8ckjhlwdwti8s/Konitor.zip?dl=0

**Comment by kwpugh** [comment]
Curios support added to latest release

**Comment by MasterSloth1** [comment]
Woooooott!!! GJ
