### ISSUE TITLE
Ring of mining Voiding ores.

### ISSUE THREAD

**Issue by litjohn50** [kwpugh/Gobber#7]
In the previous versions the Ring of mining pretty much only mined stone. So normally you would shift right-click to not get cobble spammed in your inventory. 

Now when you shift-right-click it deletes stone and various different ores. It even deletes vanilla redstone ore.

Video of it doing it: https://gyazo.com/14c57916c407550cdcb7b2043fa944b8

(side note) You can right click all your base away now. It breaks "Yamada's" mining portal dim, and "Metal barrels" storage barrels. (Probably other things as well)

**Comment by kwpugh** [comment]
Ok, I’ll take a look tonight when I get home.   In an attempt to include more variety of stone added by other mods, I might have gone overboard.  Thanks for the heads up

**Comment by kwpugh** [comment]
I reverted the old Ring of the Miner "inclusion only" behavior in the v54 release.   I will have to investigate more for a safer option to remove unwanted blocks (other mods) while mining.
