### ISSUE TITLE
[1.16.3] Gobber Not Compatible with Advanced Mining Dimension

### ISSUE THREAD

**Issue by ClaudiusMinimus** [kwpugh/gobber#70]
I'm making a modpack using Gobber and Easy Steel. The ores from both mods are not generating within the [Advanced Mining Dimension](https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension/files/3061058) as expected. I have posted this issue with henkelmax (dev for mining dimension) as shown [here](https://github.com/henkelmax/advanced-mining-dimension/issues/9). He suggested a datapack, which I have tried without success. Since both your mods and the mining dimension are popular mods, it would be nice if your mods could generate ores in the mining dimension.

The pack is not published yet, but here is the latest Twitch/MultiMC install: 
[Paradise in Chaos-0.2.0.zip](https://github.com/kwpugh/gobber/files/5258291/Paradise.in.Chaos-0.2.0.zip)

Forge: 34.0.9
Minecraft: 1.16.3
Gobber2-1.16.3-2.3.9
EasySteel-1.16.3-1.2.4

**Comment by kwpugh** [comment]
There doesn't appear a way to do this with the current state of Forge.   Will re-visit after the Forge biome API gets worked out.

**Comment by kwpugh** [comment]
not present in latest Forge and Gobber.   No longer supporting 1.16.3.
