### ISSUE TITLE
[1.16.3] Null underground generation on newest forge versions

### ISSUE THREAD

**Issue by cabaleiro** [kwpugh/gobber#71]
`
[Render thread/INFO] [minecraft/SaveFormat]: Attempt 1...

[Render thread/ERROR] [minecraft/BiomeGenerationSettings]: Feature: Not a JSON object: "minecraft:disk_gravel"; Not a JSON object: "minecraft:disk_clay"; Not a JSON object: "minecraft:disk_sand"; Not a JSON object: "minecraft:ore_lapis"; Not a JSON object: "minecraft:ore_diamond"; Not a JSON object: "minecraft:ore_redstone"; Not a JSON object: "minecraft:ore_gold"; Not a JSON object: "minecraft:ore_iron"; Not a JSON object: "minecraft:ore_coal"; Not a JSON object: "minecraft:ore_andesite"; Not a JSON object: "minecraft:ore_diorite"; Not a JSON object: "minecraft:ore_granite"; Not a JSON object: "minecraft:ore_gravel"; Not a JSON object: "minecraft:ore_dirt"`

Tested on Gobber2-2.3.9 and 2.3.10. The console will spam this message on accessing world creation screen AND upon entering a world. The in-world result is that the underground is solely made of the minecraft:stone block. No ores, dirt, or any of the blocks mentioned on the list. No own generation from the mod either.

**Comment by kwpugh** [comment]
On going issue with Forge 1.16.3 ore gen.   Working on it.

**Comment by kwpugh** [comment]
Is this happening with stand-alone or with other mods installed?

Reason I ask is that my mods ore get seems to work well with most other mods, but not with some.   Currently, there is no standard way of ore gen which causes cross-mod conflicts.

Can you please provide a list of other mods you are using that generate ore or decorate biomes?   This will help/

**Comment by kwpugh** [comment]
![2020-10-01_12 16 56](https://user-images.githubusercontent.com/8809210/94841825-2e57dd80-03e0-11eb-84ab-6e184f3d5848.png)

Gobber with a bunch of other mods that generate ores.
