### ISSUE TITLE
[1.16.3] Crash - updating to forge-34.1.5 resolved

### ISSUE THREAD

**Issue by Tyrius1** [kwpugh/gobber#72]
Minecraft 1.16.3
Gobber2-1.16.3-2.3.10
forge-34.1.1

Upon joining into a world client crashes
when removing gobber crash stops
crash report:
https://pastebin.com/j3mDZRBk
Log:
[2020-10-03-7.log](https://github.com/kwpugh/gobber/files/5321887/2020-10-03-7.log)

**Comment by Tyrius1** [comment]
[latest.log](https://github.com/kwpugh/gobber/files/5321903/latest.log)
after updating to 34.1.5

**Comment by kwpugh** [comment]
Try this version for me please.

[Gobber2-1.16.3-2.3.12.jar.zip](https://github.com/kwpugh/gobber/files/5323527/Gobber2-1.16.3-2.3.12.jar.zip)

Also, did you have an Experience Medallion and killing a Creeper when this crash happened?

**Comment by Tyrius1** [comment]
Sorry it took so long to get back,
that version you shared does indeed fix the issue!

no i wasnt using experience medallion while killing a creeper though

it was basically crashing soon as the world would attempt to load or within a few seconds directly after it loaded.

**Comment by kwpugh** [comment]
Good.   I will publish the new version then.
