### ISSUE TITLE
[1.15.2] Items can break blocks claimed with FTB chunks

### ISSUE THREAD

**Issue by Intezium** [kwpugh/gobber#73]
The player must be on the chunk without claims, and there must be a claimed chunk near it.
1) Ring of the Miner
2) Ring of the Lumberjack
3) Ring of the Farmer
4) Ring of Husbandry
5) Ring of Blink
6) Staff of Clearing
7) Staff of the Harvest
8) Gobber Hammer
9) Nether Hammer
10) End Hammer
11) Gobber  Excavator
12) Nether Excavator
13) End Excavator

**Comment by kwpugh** [comment]
Sent a message to LatvianModder to find out where in his code the blocks are protected by a claim.

**Comment by kwpugh** [comment]
problem doesn't exist in 1.16.4.  I will not be fixing in 1.15.2.
