### ISSUE TITLE
[1.16.3] Crash with Wither

### ISSUE THREAD

**Issue by Taccio33** [kwpugh/gobber#77]
[crash-2020-10-28_12.41.11-server.txt](https://github.com/kwpugh/gobber/files/5453382/crash-2020-10-28_12.41.11-server.txt)
[crash-2020-10-28_12.49.40-server.txt](https://github.com/kwpugh/gobber/files/5453383/crash-2020-10-28_12.49.40-server.txt)
the only thing is that I'm using the .25 forge instead of the .33 for compatibility reasons

**Comment by kwpugh** [comment]
What were you doing when it crashed?

**Comment by kwpugh** [comment]
[Gobber2-1.16.3-2.3.17.jar.zip](https://github.com/kwpugh/gobber/files/5455544/Gobber2-1.16.3-2.3.17.jar.zip)

Try this version for me and let me know if it still crashes.

**Comment by kwpugh** [comment]
[Gobber2-1.16.3-2.3.17a.jar.zip](https://github.com/kwpugh/gobber/files/5455783/Gobber2-1.16.3-2.3.17a.jar.zip)

Test this one instead, pretty sure I got it.

**Comment by Taccio33** [comment]
gonna try it right now!

**Comment by Taccio33** [comment]
Yes, it appears to fix both spawning and projectile explosions! thank you very much

**Comment by kwpugh** [comment]
New version published to Curseforge.
