### ISSUE TITLE
[1.16.3] Issue with ring of the explorer

### ISSUE THREAD

**Issue by lacomarca** [kwpugh/gobber#78]
Hi,

I'm having an issue with this ring. When I right click to use it, a message appears in console and server crash. Could you take a look? I'm using 1.16.3 version, forge 34.1.19 and Gobber2-1.16.3-2.3.13 Thanks a lot in advance! Message in console and crash report below.

Message in console:

03.11 17:58:31 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
03.11 17:58:31 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.util.CooldownTracker.func_185142_b(Lnet/minecraft/item/Item;)V
03.11 17:58:31 [Server] INFO at com.kwpugh.gobber2.items.rings.ItemCustomRingExplorer.func_77659_a(ItemCustomRingExplorer.java:76) ~[?:2.3.13] {re:classloading,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?] {re:computing_frames,re:classloading}
03.11 17:58:31 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:913) ~[?:?] {re:classloading,pl:accesstransformer:B}
03.11 17:58:31 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?] {re:classloading}
03.11 17:58:31 [Server] INFO at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
03.11 17:58:31 [Server] INFO at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
03.11 17:58:31 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
03.11 17:58:31 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
03.11 17:58:31 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
03.11 17:58:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:730) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
03.11 17:58:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:707) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
03.11 17:58:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
03.11 17:58:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
03.11 17:58:31 [Server] Server thread/FATAL [ne.mi.co.ForgeMod/]: Preparing crash report with UUID a9d0edb6-78a9-49af-b47d-06a7f2821eb5

Crash report:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/3/20 4:58 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.util.CooldownTracker.func_185142_b(Lnet/minecraft/item/Item;)V
	at com.kwpugh.gobber2.items.rings.ItemCustomRingExplorer.func_77659_a(ItemCustomRingExplorer.java:76) ~[?:2.3.13] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:913) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:730) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:707) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/3/20 4:58 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.util.CooldownTracker.func_185142_b(Lnet/minecraft/item/Item;)V
	at com.kwpugh.gobber2.items.rings.ItemCustomRingExplorer.func_77659_a(ItemCustomRingExplorer.java:76) ~[?:2.3.13] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:214) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:913) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:730) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:707) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 4.4.232-1.el7.elrepo.x86_64
	Java Version: 1.8.0_265, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 3054516872 bytes (2913 MB) / 8424783872 bytes (8034 MB) up to 9320792064 bytes (8889 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx10000M -Xms128M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/custom.jar object_holder_definalize PLUGINSERVICE 
		/custom.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/custom.jar capability_inject_definalize PLUGINSERVICE 
		/custom.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/custom.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.19
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		rsrequestify-1.16.3-2.0.jar RSRequestify {rsrequestify@2.0 DONE}
		DungeonsMod-1.16.3-1.0.15.jar Dungeons Mod {dungeonsmod@1.16.3-1.0.15 DONE}
		NetherPortalFix_1.16.3-7.2.0.jar NetherPortalFix {netherportalfix@7.2.0 DONE}
		mcw-windows-1.0.2-mc1.16.3.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		rsgauges-1.16.3-1.2.4.jar Gauges and Switches {rsgauges@1.2.4 DONE}
		ForgeEndertech-1.16.3-7.0.4.0-build.0017.jar Forge Endertech {forgeendertech@7.0.4.0 DONE}
		XaerosWorldMap_1.11.0_Forge_1.16.3.jar Xaero's World Map {xaeroworldmap@1.11.0 DONE}
		CookingForBlockheads_1.16.3-9.2.1.jar Cooking for Blockheads {cookingforblockheads@9.2.1 DONE}
		ReAuth-1.16-Forge-3.9.2.jar ReAuth {reauth@3.9.2 DONE}
		dankstorage-3.11.jar Dank Storage {dankstorage@3.11 DONE}
		ftb-gui-library-1603.1.1.24.jar FTB GUI Library {ftbguilibrary@1603.1.1.24 DONE}
		Bookshelf-1.16.3-8.5.17.jar Bookshelf {bookshelf@8.5.17 DONE}
		DarkUtilities-1.16.3-6.0.1.jar Dark Utilities {darkutils@6.0.1 DONE}
		Morpheus-1.16.3-4.2.59.jar Morpheus {morpheus@version DONE}
		sworddisplay-1.16.2-1.0.3..jar Sword Displays {sworddisplay@1.16.2-1.0.3. DONE}
		MekanismGenerators-1.16.3-10.0.11.436.jar Mekanism: Generators {mekanismgenerators@10.0.11 DONE}
		Hwyla-forge-1.10.11-B78_1.16.2.jar Waila {waila@1.10.11-B78_1.16.2 DONE}
		Ma-Essentials-1.16.3-3.4.0.jar Ma Essentials {maessentials@1.16.3-3.4.0 DONE}
		FpsReducer-mc1.16.3-1.18.jar FPS Reducer {fpsreducer@mc1.16.3-1.18 DONE}
		shetiphiancore-1.16-3.8.2.jar ShetiPhian-Core {shetiphiancore@3.8.2 DONE}
		extra-foods-1.16.3-1.1.0.jar Extra Foods {extrafoods@1.16.3-1.1.0 DONE}
		emojiful-1.16.3-2.1.0.jar Emojiful {emojiful@1.16.3-2.1.0 DONE}
		refinedstorage-1.9.8.jar Refined Storage {refinedstorage@1.9.8 DONE}
		SimpleOres2-1.16.3-2.3.1.0.jar Simple Ores {simpleores@1.16.3-2.3.1.0 DONE}
		EnderTendril-1.16.3-1.1.1+4.jar Ender Tendril {endertendril@1.1.1+4 DONE}
		corpse-1.16.3-1.1.8.jar Corpse {corpse@1.16.3-1.1.8 DONE}
		anviltweaks-3.1.jar Anvil Tweaks {anviltweaks@3.1 DONE}
		AmbientSounds_v3.0.21_mc1.16.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		crashutilities-3.5.jar Crash Utilities {crashutilities@3.5 DONE}
		BiomesOPlenty-1.16.3-12.0.0.409-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.409 DONE}
		MekanismAdditions-1.16.3-10.0.11.436.jar Mekanism: Additions {mekanismadditions@10.0.11 DONE}
		Beekeeper-1.16.2-1.0.0.3.jar Beekeeper {bk@1.0.0.3 DONE}
		valhelsia_structures-16.0.3.jar Valhelsia Structures {valhelsia_structures@16.0.3 DONE}
		RapidLeafDecay-1.16.3-1.0.0.jar Rapid Leaf Decay {rapid_leaf_decay@1.0.0 DONE}
		SimpleCoreLib-1.16.3-2.0.1.2.jar SimpleCoreLib {simplecorelib@1.16.3-2.0.1.2 DONE}
		Block-History-1.16.3-1.1.0.jar Block History {blockhistory@1.1.0 DONE}
		simplylight-1.16.3-1.0.2.jar Simply Light {simplylight@1.16.3-1.0.2 DONE}
		simplefarming-1.16.3-1.3.3.jar Simple Farming {simplefarming@1.16.3-1.3.3 DONE}
		xercamod-1.16.3-1.1.jar Xerca Mod {xercamod@1.16.3-1.1 DONE}
		simplybackpacks-1.16.3-1.4.13.jar Simply Backpacks {simplybackpacks@1.16.3-1.4.13 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		Botania-1.16.3-409.jar Botania {botania@1.16.3-409 DONE}
		Patchouli-1.16.2-47.jar Patchouli {patchouli@1.16.2-47 DONE}
		collective-1.16.3-1.51.jar Collective {collective@1.51 DONE}
		camera-1.16.3-1.0.3.jar Camera Mod {camera@1.16.3-1.0.3 DONE}
		lottaterracotta-1.16.3-1.3.1.jar Lotta Terracotta {lottaterracotta@1.16.3-1.3.1 DONE}
		elevatorid-1.16.3-1.7.6.jar Elevator Mod {elevatorid@1.16.3-1.7.6 DONE}
		Gobber2-1.16.3-2.3.13.jar Gobber 2 {gobber2@2.3.13 DONE}
		buildersaddition-1.16.3-20200930a.jar Builders Crafts & Addition {buildersaddition@1.16.3-20200930a DONE}
		ExtraStorage-1.16.3-1.1.1.jar Extra Storage {extrastorage@1.1.1 DONE}
		starterkit_1.16.3-2.1.jar Starter Kit {starterkit@2.1 DONE}
		MekanismTools-1.16.3-10.0.11.436.jar Mekanism: Tools {mekanismtools@10.0.11 DONE}
		constructionwand-1.16.2-1.5.jar Construction Wand {constructionwand@1.16.2-1.5 DONE}
		mcws-roofs-1.16.3-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		furniture-7.0.0-pre19-1.16.3.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre19 DONE}
		curiouselytra-forge-1.16.3-4.0.0.1.jar Curious Elytra {curiouselytra@1.16.3-4.0.0.1 DONE}
		AI-Improvements-1.16.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		globalxp-1.16.3-v1.4.14.jar Global XP {globalxp@v1.4.14 DONE}
		productivebees-1.16.3-0.4.1.4.jar Productive Bees {productivebees@1.16.3-0.4.1.4 DONE}
		DarkPaintings-1.16.3-4.0.2.jar DarkPaintings {darkpaintings@4.0.2 DONE}
		BetterAdvancements-1.16.3-0.1.0.102.jar Better Advancements {betteradvancements@0.1.0.102 DONE}
		doubledoors_1.16.3_2.1.jar Double Doors {doubledoors@2.1 DONE}
		flesh2leather-1.0.1.jar Flesh2Leather {flesh2leather@1.0.1 DONE}
		forgeautofish-1.0.5-1.16.3.jar AutoFish for Forge {forgeautofish@1.0.5 DONE}
		TrashSlot_1.16.3-12.2.0.jar TrashSlot {trashslot@12.2.0 DONE}
		mining-helmet-1.16.3-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		CustomSkinLoader_Forge-14.13-SNAPSHOT-182.jar CustomSkinLoader {customskinloader@14.13-SNAPSHOT-182 DONE}
		treeharvester_1.16.3-1.6.jar Tree Harvester {treeharvester@1.6 DONE}
		jei-1.16.3-7.6.0.49.jar Just Enough Items {jei@7.5.0.43 DONE}
		justmobheads_1.16.3-3.7.jar Just Mob Heads {justmobheads@3.7 DONE}
		seals-1.16.3-2.0.0.jar Seals {seals@2.0.0 DONE}
		Mekanism-1.16.3-10.0.11.436.jar Mekanism {mekanism@10.0.11 DONE}
		caelus-forge-1.16.3-2.0.0.3.jar Caelus API {caelus@1.16.3-2.0.0.3 DONE}
		reap-1.16.3-1.0.2.jar Reap Mod {reap@1.16.3-1.0.2 DONE}
		WAWLA-1.16.3-6.0.1.jar WAWLA {wawla@6.0.1 DONE}
		Waystones_1.16.3-7.3.0.jar Waystones {waystones@7.3.0 DONE}
		Clumps-6.0.0.11.jar Clumps {clumps@6.0.0.11 DONE}
		sweetconcrete-1.16.3-1.7.1.jar Sweet Concrete {sweetconcrete@1.16.3-1.7.1 DONE}
		comforts-forge-1.16.3-4.0.0.1.jar Comforts {comforts@1.16.3-4.0.0.1 DONE}
		NaturesCompass-1.16.3-1.8.5.jar Nature's Compass {naturescompass@1.16.3-1.8.5 DONE}
		FruitTrees-1.16.3-2.1.0.jar Fruit Trees {fruittrees@2.1.0 DONE}
		Kiwi-1.16.3-3.4.0.jar Kiwi {kiwi@3.4.0 DONE}
		[1.16.3]-additionalbars-1.5.2.jar Additional Bars {additionalbars@1.5.2 DONE}
		LibX-1.16.3-1.0.1.jar LibX {libx@1.16.3-1.0.1 DONE}
		decorative_blocks-1.16.2-1.1.jar Decorative Blocks {decorative_blocks@1.5 DONE}
		BotanyPots-1.16.3-5.1.9.jar BotanyPots {botanypots@5.1.9 DONE}
		BotanyTrees-1.16.3-1.0.7.jar BotanyTrees {botanytrees@1.0.7 DONE}
		DungeonCrawl-1.16.3-2.1.1.jar Dungeon Crawl {dungeoncrawl@2.1.1 DONE}
		FarmingForBlockheads_1.16.3-7.2.0.jar Farming for Blockheads {farmingforblockheads@7.2.0 DONE}
		mapperbase-1.16.3-2.1.0.1.jar Mapper Base {mapperbase@1.16.3-2.1.0.1 DONE}
		embellishcraft-1.16.3-3.1.0.1.jar EmbellishCraft {embellishcraft@1.16.3-3.1.0.1 DONE}
		embellishcraft-bop-1.16.3-3.1.0.jar EmbellishCraft BoP Addon {embellishcraft-bop@1.16.3-3.1.0 DONE}
		additional_lights-1.16.3-2.1.2.jar Additional Lights {additional_lights@2.1.2 DONE}
		travellersboots-1.16.x-1.4.3.jar Traveller's Boots {travellersboots@1.4.3 DONE}
		CraftTweaker-1.16.3-7.0.0.45.jar CraftTweaker {crafttweaker@7.0.0.45 DONE}
		ftb-chunks-1.1.2.36.jar FTB Chunks {ftbchunks@1.1.2.36 DONE}
		forge-1.16.3-34.1.19-universal.jar Forge {forge@34.1.19 DONE}
		Waddles-1.16.3-0.8.9.jar Waddles {waddles@1.16.3-0.8.9 DONE}
		WailaHarvestability-mc1.16.2-forge-1.1.13.jar Waila Harvestability {wailaharvestability@1.1.13 DONE}
		VendingMachine-1.16.2-1.0.0.3.jar Vending Machine {vm@1.0.0.3 DONE}
		amb-1.16.3-0.1.0.jar Aurum's More Blocks {amb@1.16.3-0.1.0 DONE}
		CraftingTweaks_1.16.3-12.2.0.jar Crafting Tweaks {craftingtweaks@12.2.0 DONE}
		forge-1.16.3-34.1.19-server.jar Minecraft {minecraft@1.16.3 DONE}
		EnchantmentDescriptions-1.16.3-5.0.1.jar EnchantmentDescriptions {enchdesc@5.0.1 DONE}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.16.3-1.15.1.jar Tool Belt {toolbelt@1.15.1 DONE}
		durability101-1.16-0.0.3.jar Durability101 {durability101@0.0.3 DONE}
		baubles-1.8.2-1.16.3.jar Baubles {baubles@1.8.2 DONE}
		pamhc2crops-1.16.3-1.0.1.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		AdLods-1.16.3-4.0.2.1-build.0018.jar Large Ore Deposits {adlods@4.0.2.1 DONE}
		jeiintegration_1.16.3-6.0.0.8.jar JEI Integration {jeiintegration@6.0.0.8 DONE}
		Mantle-1.16.3-1.6.40.jar Mantle {mantle@1.6.40 DONE}
		Inspirations-1.16.3-1.2.1.19.jar Inspirations {inspirations@1.2.1 DONE}
		Xaeros_Minimap_20.25.1_Forge_1.16.3.jar Xaero's Minimap {xaerominimap@20.25.1 DONE}
		pamhc2foodcore-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		ftb-backups-2.1.1.6.jar FTB Backups {ftbbackups@2.1.1.6 DONE}
		cyclepaintings_1.16.3-1.4.jar Cycle Paintings {cyclepaintings@1.4 DONE}
		polymorph-forge-1.16.3-0.15.jar Polymorph {polymorph@1.16.3-0.15 DONE}
		[1.16.2]+SecurityCraft+v1.8.19.3.jar SecurityCraft {securitycraft@v1.8.19.3 DONE}
		sit-1.16.2-v1.3.jar Sit {sit@v1.3 DONE}
		earthmobsmod-1.16.3-0.1.2-Beta.jar Earth Mobs Mod {earthmobsmod@1.16.3-0.1.2-Beta DONE}
		HardcoreRevival_1.16.3-5.2.0.jar Hardcore Revival {hardcorerevival@5.2.0 DONE}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.16.3-1.1.3-b1.jar Engineer's Decor {engineersdecor@1.1.3-b1 DONE}
		connectedglass-1.0.6-mc1.16.3.jar Connected Glass {connectedglass@1.0.6 DONE}
		moredragoneggs-1.4.jar More Dragon Eggs {moredragoneggs@1.4 DONE}
		Aquaculture-1.16.3-2.1.1.jar Aquaculture 2 {aquaculture@1.16.3-2.1.1 DONE}
		refinedstorageaddons-0.7.2.jar Refined Storage Addons {refinedstorageaddons@0.7.2 DONE}
		terraqueous-1.16-1.7.3.jar Terraqueous {terraqueous@1.7.3 DONE, terraheads@1.0.0 DONE, pixelpowers@2.0.0 DONE}
		CosmeticArmorReworked-1.16.3-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.3-v1 DONE}
		botanicalmachinery-1.16.3-0.2.1.jar Botanical Machinery {botanicalmachinery@0.2.1 DONE}
		chiselsandbits-0.2.1-ALPHA.jar Chisels & bits {chiselsandbits@NONE DONE}
		deuf-1.16.3-1.1.jar DEUF - Duplicate Entity UUID Fix {deuf@1.16.3-1.1 DONE}
	Crash Report UUID: a9d0edb6-78a9-49af-b47d-06a7f2821eb5
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:core
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
	Player Count: 2 / 100; [ServerPlayerEntity['Daiyumi'/1127, l='ServerLevel[world]', x=2308.59, y=67.00, z=335.79], ServerPlayerEntity['Arwen150'/35896, l='ServerLevel[world]', x=-969.86, y=67.00, z=-1015.38]]
	Data Packs: vanilla, mod:rsrequestify (incompatible), mod:netherportalfix (incompatible), mod:mcwwindows (incompatible), mod:rsgauges, mod:forgeendertech, mod:xaeroworldmap, mod:cookingforblockheads (incompatible), mod:reauth, mod:dankstorage (incompatible), mod:ftbguilibrary (incompatible), mod:bookshelf, mod:darkutils (incompatible), mod:morpheus (incompatible), mod:sworddisplay, mod:mekanismgenerators, mod:waila, mod:maessentials (incompatible), mod:fpsreducer, mod:shetiphiancore, mod:extrafoods, mod:emojiful (incompatible), mod:refinedstorage, mod:simpleores, mod:endertendril (incompatible), mod:anviltweaks (incompatible), mod:ambientsounds (incompatible), mod:crashutilities (incompatible), mod:biomesoplenty (incompatible), mod:mekanismadditions, mod:bk, mod:valhelsia_structures (incompatible), mod:rapid_leaf_decay, mod:simplecorelib, mod:simplylight, mod:simplefarming, mod:xercamod (incompatible), mod:simplybackpacks (incompatible), mod:curios, mod:collective, mod:camera, mod:lottaterracotta (incompatible), mod:elevatorid (incompatible), mod:gobber2 (incompatible), mod:buildersaddition (incompatible), mod:extrastorage, mod:starterkit, mod:mekanismtools, mod:mcwroofs (incompatible), mod:cfm (incompatible), mod:curiouselytra, mod:aiimprovements, mod:globalxp, mod:darkpaintings (incompatible), mod:betteradvancements, mod:doubledoors, mod:flesh2leather (incompatible), mod:forgeautofish (incompatible), mod:trashslot (incompatible), mod:mining_helmet (incompatible), mod:customskinloader (incompatible), mod:treeharvester, mod:jei, mod:justmobheads, mod:seals (incompatible), mod:mekanism, mod:caelus, mod:reap, mod:wawla, mod:waystones (incompatible), mod:clumps (incompatible), mod:sweetconcrete (incompatible), mod:comforts (incompatible), mod:naturescompass (incompatible), mod:fruittrees, mod:kiwi (incompatible), mod:additionalbars, mod:decorative_blocks, mod:botanypots, mod:botanytrees, mod:dungeoncrawl, mod:farmingforblockheads (incompatible), mod:mapperbase (incompatible), mod:embellishcraft (incompatible), mod:embellishcraft-bop (incompatible), mod:additional_lights, mod:travellersboots (incompatible), mod:crafttweaker, mod:ftbchunks (incompatible), mod:forge, mod:waddles, mod:wailaharvestability, mod:vm, mod:amb (incompatible), mod:craftingtweaks (incompatible), mod:enchdesc, mod:mousetweaks, mod:toolbelt (incompatible), mod:durability101 (incompatible), mod:baubles (incompatible), mod:pamhc2crops (incompatible), mod:adlods, mod:jeiintegration, mod:mantle (incompatible), mod:inspirations (incompatible), mod:xaerominimap, mod:pamhc2foodcore (incompatible), mod:ftbbackups (incompatible), mod:cyclepaintings, mod:polymorph (incompatible), mod:securitycraft (incompatible), mod:sit, mod:earthmobsmod (incompatible), mod:hardcorerevival (incompatible), mod:appleskin, mod:engineersdecor, mod:connectedglass (incompatible), mod:aquaculture (incompatible), mod:refinedstorageaddons, mod:terraqueous, mod:cosmeticarmorreworked (incompatible), mod:deuf (incompatible), mod:constructionwand (incompatible), mod:dungeonsmod, mod:corpse, mod:blockhistory, mod:botania, mod:patchouli (incompatible), mod:productivebees (incompatible), mod:libx, mod:botanicalmachinery, mod:chiselsandbits (incompatible), mod:moredragoneggs (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by kwpugh** [comment]
Fixed in next release
