### ISSUE TITLE
[suggestion] have the staff of the stars make a noise when successfully placing a torch

### ISSUE THREAD

**Issue by Knito58** [kwpugh/gobber#8]
Yes, it's totally silent. Would be great if it made the same noise as if I placed a normal torch by hand. And as this is assumed to happen magically some extra particles saying "I was made by magic" would be appreciated.

This great tool is allowed to show its grace by sounding and lighting. Does not need to be as humble as quite now.

And if you ever do it, then do not forget the corresponding end paxle.

Great mod! Thank you.

**Comment by kwpugh** [comment]
This should be straight forward, I will take a look.

**Comment by Knito58** [comment]
:)

**Comment by kwpugh** [comment]
Will be fixed in the next release.

**Comment by Knito58** [comment]
Fix confirmed, thank you.
