### ISSUE TITLE
[1.16.4] Harvest level issue with Silent Gear pickaxes

### ISSUE THREAD

**Issue by TwilightPSN** [kwpugh/gobber#80]
When mining gobber ores with a pick from Silent's Gear that has the appropriate level to mine it, the ore just breaks and doesnt drop anything.

**Comment by kwpugh** [comment]
Which pick?   Is it diamond level?

**Comment by TwilightPSN** [comment]
It was an obsidian level pick which wayla also said the ore needed.
https://i.imgur.com/torZvXB.png

**Comment by kwpugh** [comment]
I recommend using a real diamond pickaxe.   Not sure how a lead pickaxe is diamond level.

It will take me some time to look at Silent's code to see what they are doing.

**Comment by kwpugh** [comment]
We are talking gobber ore in the overworld, not the nether or end gobber ore, correct?

**Comment by TwilightPSN** [comment]
That is correct in the overworld

**Comment by kwpugh** [comment]
Which mod are you getting the Lead from to make the pickaxe?

**Comment by TwilightPSN** [comment]
every lead ore gets converted to mekanism lead in my pack im starting to think it may be a tooltip error in wayla

**Comment by kwpugh** [comment]
Might try The One Probe and see it you get the same result.    I have never used Silents Gear, so I don't even know how to make a tool, let alone your particular combination.

**Comment by TwilightPSN** [comment]
TOP displays the same information and i have even changed the silents gear pick to some silents gem pieces of which are diamond level mining. It may be a compat issue between the mods.

**Comment by kwpugh** [comment]
Yeah, not sure.  I'm using the standard Forge harvest level api and Silent is using a custom built systems.   I may shot them a message and ask about it.

**Comment by kwpugh** [comment]
Feedback from Silent:

<img width="710" alt="Screen Shot 2020-11-18 at 8 39 27 AM" src="https://user-images.githubusercontent.com/8809210/99544219-acb11480-2979-11eb-8db2-06509905451a.png">

**Comment by kwpugh** [comment]
Try holding shift as Silent suggests and confirm the actual harvest level please.

**Comment by TwilightPSN** [comment]
I had a tool last night from silent gear that was diamond level and same issue. Can get a screenshot of the tooltip for you later if you would like it’s made from silent gems pieces as mentioned above so different than that lead one.

**Comment by kwpugh** [comment]
can you confirm with an actual diamond pickaxe, too rule out something else interferring

**Comment by SephirothWS** [comment]
![image](https://i.imgur.com/c6JWhs5.png)
Cannot mine Gobber Ore
![Image2](https://i.imgur.com/P5wXEmD.png)
Could mine Gobber Ore

**Comment by kwpugh** [comment]
ok, thanks for checking in.

**Comment by SephirothWS** [comment]
@kwpugh So what's the deal, is it tools capable of mining diamonds or obsidian that's the requirement for Gobber Ore?

**Comment by kwpugh** [comment]
Gobber ore requires a diamond pickaxe, or any pickaxe with harvest level 3.
