### ISSUE TITLE
Curios seams to be a required dependency

### ISSUE THREAD

**Issue by cryxli** [kwpugh/gobber#81]
### Summary

Looking at the crash report:
[crash-2020-11-21_20.57.23-client.txt](https://github.com/kwpugh/gobber/files/5579178/crash-2020-11-21_20.57.23-client.txt)

Ring of Attraction tries to instantiate top.theillusivec4.curios.api.SlotTypeInfo$BuildScheme

### Setup

- Minecraft 1.16.3
- Fabric API 0.25.0+build.415-1.16
- Ring Of Attraction 1.0.26

### Effect

Game crashes with the above report. That indicates a missing class.

**Comment by kwpugh** [comment]
I'm checking in with C4 to see what I did wrong.

**Comment by kwpugh** [comment]
Indicated the Curios API is required on the mod page.
