### ISSUE TITLE
[1.16.4] Block breaking issue with Hammers without Material values

### ISSUE THREAD

**Issue by TwilightPSN** [kwpugh/gobber#82]
Have come across a couple of issues with the way Gobber handles breaking blocks. It seems the issue is something on the end of Gobber that cannot be fixed by the other mod devs the interation is with.

https://github.com/Qelifern/IronFurnaces/issues/22
https://github.com/HellFirePvP/AstralSorcery/issues/1480 (Where they said the issue is)

**Comment by kwpugh** [comment]
I think I know why, those mods are not setting a material value when they register their blocks.   I will have to look at other options.   What other hammers did you try that DID work?

**Comment by TwilightPSN** [comment]
Vanilla Hammers mod works just fine with them

**Comment by kwpugh** [comment]
cool, thx

**Comment by kwpugh** [comment]
this mostly for my ref so I remember later, but vanilla hammers is using the same  world.removeBlock(pos, false) and spawning drops, they just have a lot more code up front doing checks.

`    public static void breakInRadius(World world, PlayerEntity playerEntity, int radius, IBreakValidator breakValidator) {
        if (!world.isRemote) {
            List<BlockPos> brokenBlocks = getBreakBlocks(world, playerEntity, radius);
            ItemStack heldItem = playerEntity.getHeldItemMainhand();
            IItemTier toolMaterial = ((BigBreakItem) heldItem.getItem()).getToolMaterial();
            int silktouch = EnchantmentHelper.getEnchantmentLevel(Enchantments.SILK_TOUCH, heldItem);
            int fortune = EnchantmentHelper.getEnchantmentLevel(Enchantments.FORTUNE, heldItem);
            for (BlockPos pos : brokenBlocks) {
                BlockState state = world.getBlockState(pos);
                if (breakValidator.canBreak(state)) {
                    if (playerEntity.abilities.isCreativeMode) {
                        if (state.removedByPlayer(world, pos, playerEntity, true, state.getFluidState()))
                            state.getBlock().onPlayerDestroy(world, pos, state);
                    } else {
                        heldItem.getItem().onBlockDestroyed(heldItem, world, state, pos, playerEntity);
                        TileEntity tileEntity = world.getTileEntity(pos);
                        state.getBlock().onPlayerDestroy(world, pos, state);
                        state.getBlock().harvestBlock(world, playerEntity, pos, state, tileEntity, heldItem);
                        state.getBlock().dropXpOnBlockBreak((ServerWorld) world, pos, state.getBlock().getExpDrop(state, world, pos, fortune, silktouch));
                        spawnExtraDrops(toolMaterial, world, state.getBlock(), pos, heldItem);
                    }
                    world.removeBlock(pos, false);
                    world.playEvent(2001, pos, Block.getStateId(state));
                    ((ServerPlayerEntity) playerEntity).connection.sendPacket(new SChangeBlockPacket(world, pos));
                }
            }
        }
    }`

**Comment by kwpugh** [comment]
This had not come up before, because it is standard practice to set a material value when registering blocks, which those blocks don't.

for example:
`public static final RegistryObject<Block> GOBBER2_BLOCK = BLOCKS.register("gobber2_block", () -> new BlockGobberBlock(Block.Properties.create(Material.IRON, MaterialColor.IRON).hardnessAndResistance(3.0F, 3.0F).sound(SoundType.METAL)));`

This will likely take quite a while to figure out, sorry.

**Comment by kwpugh** [comment]
Regarding the iron furnace, there isn't any reason why a tile entity needs to be broken by a player.

**Comment by Qelifern** [comment]
Working on converting to a loot_table json system instead, will be in ironfurnaces-1.16.4-2.5.4, then this will probably be fixed.

**Comment by kwpugh** [comment]
This is no longer anything I plan to fix on my end.
