### ISSUE TITLE
The Healer shows x-ray vision

### ISSUE THREAD

**Issue by ClaudiusMinimus** [kwpugh/gobber#84]
The Healer in 1.16.4 shows what is best described as x-ray vision. I noticed it with my texture pack, but other players for my pack who use vanilla also show x-ray vision.

Minecraft: 1.16.4
Forge: 35.1.28
Gobber: 1.16.4-2.3.41

![2020-12-31_15 40 48](https://user-images.githubusercontent.com/17887664/103427561-1cbcd800-4b7f-11eb-94d0-90458a6a2757.png)

**Comment by kwpugh** [comment]
Yeah, already got an issue on that, since 1.15.2 hasn't changed.   I will fix it at some point.
