### ISSUE TITLE
Ore generation

### ISSUE THREAD

**Issue by krumbel** [kwpugh/gobber#85]
Im not sure why but this mod is causing ore generation to not spawn any ore, gobber or vanilla. using Larger ore deposits and the /lods clear around command, i can see the hard line where the ore generation is normal when Gobber is off but when i turn the mod on and use the same command on new chunks the entire chunk is has no ore from ground to bedrock.

**Comment by kwpugh** [comment]
Which version of goober are you using?

Are you using Optifine?

**Comment by krumbel** [comment]
minecraft is 1.16.3 and optifine is the same version
