### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by 48004800** [kwpugh/gobber#86]
1 The bow in mod should be more powerful       lack of crossbows
2 Custom armor defense,  weapon power   and durability.
3 Invisible rings don't work when holding objects in the left hand
4 Armor keeps players from starving, so they can't eat food. Players will quickly recover their health when they are saturated. It seems that the saturation effect provided by armor doesn't work. Armor can only prevent hunger.

**Comment by kwpugh** [comment]
1. I think the bows are fine as they are; there won't be any crossbows
2. Custom abilities might come in the future, likely after 1.17 update
3. Stealth ring is designed to not work with anything in left hand, as a balance.  That way you can't go around with a sword in the left hand killing mobs that can't attack you.
4. I added a small amount of saturation/tick to the gobber armor, which didn't have any; keep in mind that the saturation effect on armors is meant to be slow
