### ISSUE TITLE
[1.16.5] Health recovery options

### ISSUE THREAD

**Issue by 48004800** [kwpugh/gobber#87]
In the new version, armor still doesn't allow players to recover quickly. Players need to take off their armor and eat food to get blood back quickly. It seems that the saturation provided by armor is invalid. But the saturation obtained by command is valid.

**Comment by kwpugh** [comment]
I don't see this happening.  Please tell me more about how you are losing saturation so quickly.  I have been playing with the armor quite a bit on a server and have not seen this happen.

**Comment by kwpugh** [comment]
I just went through and tested all four armor sets and the hunger/saturation function is indeed working.  Seeing as though you are 1 in thousands of players using this mod, I suspect you perhaps have another mod that might be conflicting.

In order to repeat the situation, what are you doing to get saturation down?   I can't lose more than one hunger bar before it is restored by the armor.

**Comment by 48004800** [comment]
My problem is the slow recovery of health. You can saturate yourself and restore your health. Compare the speed
Armor keeps players from starving.                                                                                                                                                It seems that my previous suggestion has been deleted. Is it because it's not practical?

**Comment by kwpugh** [comment]
I see your point.   It was not intended to increase the rate of health recovery, just eliminate the constant need to eat.  My Powder Power mod has a series of Health Tokens that are more geared towards Heath recovery.   I usually play with that mod along with Gobber and use the tokens for health.   I can look at making a Medallion like that for Gobber perhaps.   If the armor had it built in, the player would be virtually unkillable right away.

**Comment by kwpugh** [comment]
this has been fixed in 1.17.1 and 1.18.
