### ISSUE TITLE
[Suggestion] Gobber Furnaces that have increased speeds over the vanilla furnaces.

### ISSUE THREAD

**Issue by Merkie** [kwpugh/gobber#89]
The title explains it, just craftable furnaces that follow the gobber tiers and get increasingly faster cook times. Would be useful for players who need to smelt something quick on the go or for players who don't want to set up large super smelters. Might try and code this myself.

**Comment by kwpugh** [comment]
I have such things on my to-do list, but no plans for any new machines until well after 1.17.  Besides, there are several mods that already do tiered furnaces.  

Thank you the suggestion.

Regards.
