### ISSUE TITLE
[suggestion] Make the harvesting staffs compatible with Resynth plants

### ISSUE THREAD

**Issue by Knito58** [kwpugh/gobber#9]
Thank you for a great mod.

Another one:

Did you ever think about making farmer blocks which would be crafted with one of them staffs and also being standard, nether and end farmers? Simple vanilla chests extended to harvest and store the loot.

**Comment by kwpugh** [comment]
I will need to take a deep look into this one.  My harvest staff works on crops and plants that extend Minecraft base classes, which is what most mods do, but ReSynth creates its own base class.

**Comment by Knito58** [comment]
I do understand this point. That's a pain. It was clear that the crops are something else as the staff harvests just any minecraft crop. But I didn't think further.
I'm happy with the staffs as they are quite now. If your mod is already good a lot of people suddenly come up with ideas. If not, then nobody cares. Your mod has a lot of suggestions....

**Comment by Archesr** [comment]
To make the Resynth plants compatible with at least the bonemeal items you would need to:

Go to the settings for resynth vanilla plants (\Minecraft\Instances\(your world)\config\resynth\vanilla-plants.toml)

Change enable-bonemeal to true (enable-bonemeal = true) on any (or all) plants you wish to be affected by the Ring and Staff of the Farmer.

This does not affect the Staff of The Harvest as the Resynth plants require different actions.

**Comment by Knito58** [comment]
Thank you @Archesr. I'll close this request as the enhancement does not make sense anymore with your explanation. Everybody can decide on its own how it should work by changing the config file.
