### ISSUE TITLE
ores not spawning

### ISSUE THREAD

**Issue by NoDreamsRemain** [kwpugh/gobber#90]
Im mining almost 1 hour trying to find the gobber ore to start to get the dragon armor but i cant find ONE ore. I created the world before installing the mod. Could be that the issue?

**Comment by NoDreamsRemain** [comment]
btw i have much stuff on that world so i cant just elete it and create another

**Comment by kwpugh** [comment]
if you added Gobber after creating the world, you will have to travel to previously unexplored chunks to find Gobber ores.

- Which version of Gobber are you using?
- Are you using Optifine?  If so, what version?

**Comment by NoDreamsRemain** [comment]
im using 1.16.5 and im not using optifine due to quark mod

**Comment by kwpugh** [comment]
Have you been looking for ores in previously unexplorered areas?

**Comment by NoDreamsRemain** [comment]
> Have you been looking for ores in previously unexplorered areas?

i think so. i was 140m from my home underground mining. And i think that area i explored. I will try in other areas. thanks

**Comment by NoDreamsRemain** [comment]
well that wasnt a unexplored area so it didnt had ores (sorry if my english is bad idk how to speak much)

**Comment by NoDreamsRemain** [comment]
btw im using a phyiscs mod that when i break one block, the block that was upside of the block i mined, will fall. So i tought that strange because NO ore was appearing
