### ISSUE TITLE
Nerf Dragon armor 

### ISSUE THREAD

**Issue by NoDreamsRemain** [kwpugh/gobber#91]
Maybe Nerf the Dragon Armor. I think the creative has temporary flight and then when it ends, you can't fly untill it recharges. (if it ends when you're flying, it gives slow falling so you can't just go down. i know when we have the complete set, we dont take fall damage, but if we're in the end and the flight ends it may complicate where you can land wihout going to the void and lose all of your items.)

**Comment by kwpugh** [comment]
I have no desire to add such functionality.  I like it the way it is.
