### ISSUE TITLE
Game crash with staff of ensnarement

### ISSUE THREAD

**Issue by JelliBelli1223** [kwpugh/gobber#94]
Hi I was putting a small modlist together, and I came across a bug with just the staff of ensnarement. As the title says, when ever I click to pick up an animal, the game freezes and then crashes.

Not sure why its doing that, so maybe you can help
[Staff of ensnarement crash log.txt](https://github.com/kwpugh/gobber/files/6288976/Staff.of.ensnarement.crash.log.txt)

**Comment by kwpugh** [comment]
still cannot replicate this issue.
