### ISSUE TITLE
[1.16.x] Ring of repair repaires unrepairable items

### ISSUE THREAD

**Issue by Cheaterpaul** [kwpugh/gobber#95]
While Gopper repairs the items accordingly to `Item#isRepairable`. The standalone version https://www.curseforge.com/minecraft/mc-mods/ring-of-repair-forge just checks for `Item#isDamaged` which means it repairs even not repairable items.

**Comment by kwpugh** [comment]
Sorry, must have missed that when I re-wrote the tick handler in the standalone version.  Quick fix and will publish a new version shortly.

**Comment by kwpugh** [comment]
Fixed in v1.2.14
