### ISSUE TITLE
[1.16.5] Can't fly with dragon armor

### ISSUE THREAD

**Issue by Qucumberr** [kwpugh/gobber#96]
like title says i cannot fly with the full set of dragon armor

**Comment by kwpugh** [comment]
Can't do anything with that.  Need more info on Gobber version, forge version, other mods, etc.

Just tested latest version, flying works fine and no one else is reporting an issue, so it is likely due to a conflicting mod.  Try removing other mods that add flight.

**Comment by Natchniony** [comment]
Ok, I probably found the cause of your problem - do you have "Tons of totems" mod and/or add-on for create "create stuff additions"? In my modpack these mods conflict with dragon armor and i cannot fly

**Comment by kwpugh** [comment]
I'm guessing the problem is caused by the Ton of Totems mod, which is no longer maintained and is closed-source.

Nothing I can do about this.
