### ISSUE TITLE
Rign of repair dosent work as expected

### ISSUE THREAD

**Issue by zaze06** [kwpugh/gobber#97]
Hi i got the ling to this issue page from this mod on [curseforge](https://www.curseforge.com/minecraft/mc-mods/ring-of-repair-forge) tell me is i shuld move
but hears my problem

I have instaled the ring of repair mod and i that it was supose to raiair x durebility evry time y ticks have pased on all items in my inventory

**Comment by kwpugh** [comment]
It repairs one item at a time and cycles through the players inventory.

**Comment by zaze06** [comment]
thx :)
