### ISSUE TITLE
[1.17] suggestion

### ISSUE THREAD

**Issue by 48004800** [kwpugh/gobber#99]
1  Players can customize the damage of weapons and the protection ability of armor
{like armor ,armor_toughness}   It would be better if durability was included
2  Other mods add a lot of debuffs
It's better to customize the debuff elimination function of armor
{dragon armor}
3 Players in Dragon Armor lose their ability to fly in the twilight forest
Get to the twilight forest first, then put on the Dragon Armor. Bug will emerge
Apart from these, this mod has no shortcomings In general, it reduces the difficulty of the game.
 The planting of minerals is also interesting.

**Comment by 48004800** [comment]
https://tamaized.com/azure/twilightforest/

**Comment by 48004800** [comment]
1.16.5          Latest version

**Comment by kwpugh** [comment]
The 1.16.5 version of Gobber, the Dragon Armor only works in the (3) vanilla dimensions.  I did that intentionally as not to spoil the gameplay of other mods that add dimensions, like Twilight, Aether, etc.

**Comment by kwpugh** [comment]
Since 1.17 Forge is set to drop any day, I won't be making any changes to 1.16.5.  I will consider some of these for 1.17.  In particular, I want to break out all of the material settings for armor, tools, and weapons within the config for more tailoring.

**Comment by 48004800** [comment]
Maybe the flying function of Dragon Armor in different dimensions can be modified in config
After all, different people have different ideas
You can set the default configuration exactly as you want

**Comment by kwpugh** [comment]
Perhaps, but no changes until 1.17

**Comment by kwpugh** [comment]
Oh, dragon armor might be coming out of Gobber in 1.17, like I did on the Fabric side.

**Comment by 48004800** [comment]
Why

**Comment by 48004800** [comment]
Is that necessary

**Comment by kwpugh** [comment]
There are so many flying options already available for Forge that I find it is not worth the hassle, flying items tend to break and I really don’t like them, especially on server.

**Comment by kwpugh** [comment]
It all may be a moot point anyway since I am considering dropping Forge all together and stick with Fabric.

**Comment by 48004800** [comment]
You mean flying can lead to crash

**Comment by 48004800** [comment]
Collapse

**Comment by kwpugh** [comment]
Mods with flying items tend to conflict with one another and break

**Comment by 48004800** [comment]
ok

**Comment by kwpugh** [comment]
Fabric is so much easier to work with and learn.  There are already 900 mods out on fabric for 1.17

**Comment by 48004800** [comment]
That's a pity. I can't use this mod anymore in 1.17

**Comment by kwpugh** [comment]
Added to my list of possible features.
